### ISSUE TITLE
Multi-tenancy Support

### ISSUE THREAD

**Issue by taeold** [awinogrodzki/next-firebase-auth-edge#102]
First of all, thank you for starting this wonderful project!

GCIP has straightforward, powerful support for [multi-tenancy](https://cloud.google.com/identity-platform/docs/multi-tenancy-authentication).

I see use of `tenantId` throughout the source code, but it seems difficult to leverage the existing implementation middleware to authenticate users in a multi-tenant setup.

I've given `tenantId` support a try in https://github.com/awinogrodzki/next-firebase-auth-edge/pull/101. I've been using it successfully for my personal projects.

PR is not fully fleshed out (no tests!), but wondering if this kind of addition is worth considering and the proposed implementation is in the right direction.

If it is, happy to spend a bit more time to make sure all the i's are dotted and t's crossed.

**Comment by awinogrodzki** [comment]
@taeold tenantId support released in `next-firebase-auth-edge@0.8.8`
