### ISSUE TITLE
Is it possible to know on the client side that we have authToken cookie or if we are logged in server-wise

### ISSUE THREAD

**Issue by Vitallyz** [awinogrodzki/next-firebase-auth-edge#105]
I am logging in as per the instruction: first to Firebase, then (onSuccess) I am logging in into the /api/login.

The problem is, that when Firebase is logged in, the `user` object becomes available and my guestGuard redirects to /home. When I am in authGuard scope, FE is fetching `userMe` data from another enpoint. 

That happens too soon, and the first user fetch call happens without authToken Cookies and as a result, gets an 'unauthorised' response. 

I am getting user object and loading state using `react-firebase-hooks`. And that happens too soon. 

Is there a way to tell if the /api/login was done successfully in addition to the `user` object availability? 

I can see that there is an AuthProvider sample that is defined on a client-side, but I am a bit confused about how to use it without server-side component.  I do not use server-side redirects, and manage all redirects on FE at the moment.

Thank you!
Vitally

**Comment by Vitallyz** [comment]
@awinogrodzki Thanks for your reply. There is no issue with /api/login, and I do it right after the firebase signInWithEmailAndPassword very similar to your sample. 

The issue is when the signInWithEmailAndPassword results in success, in my AuthGuard wrapper I am getting a valid `user` object and once it happens, AuthGuard try to fetch /api/user/me which holds `userMe` object with all user data including user role (user role is used in the next ACLGuard wrapper).

So two API calls are happening at about the same time: one is /api/login, and another is /api/user/me. The /api/login will be successful, but the userMe will result in Unauthorised, as the request does not have the auth cookies yet.

Basically, I disable endpoint userME based on the Firebase `user` object. But what I should do is to disable userMe endpoint based on the "server login" status, or based on whether I have an auth cookie or not. But I can not check the auth cookie as it is hidden with httpOnly for security reasons.

```
const handleSignInWithGoogle = () => {
    setGmailIsLoading(true);
    const provider = new GoogleAuthProvider();
    provider.setCustomParameters({ prompt: 'select_account' });
    signInWithPopup(auth, provider)
      .then(result => {
        serverSideSignIn(result)
          .then(() => {
            setGmailIsLoading(false);
            console.log('Server side login success');
            router.replace('/');
          })
          .catch(error => console.log('Server side login error: ', error));
        console.log('Signin result user uid: ', result.user.uid);
      })
      .catch(error => {
        setGmailIsLoading(false);
        console.log('Error signin in with Google: ', error);
      });
  };
```

```
export const serverSideSignIn = async (userCredential: UserCredential) => {
  return userCredential.user
    .getIdToken()
    .then(token => {
      console.log('Signin token: ', token);
      axiosApiClient
        .get('/login', {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        })
        .then(result => console.log('Serverside signin result: ', result))
        .catch(error => console.log('Server side signin ERROR: ', error));
    })
    .catch(error => console.log('Error getting rtoken from user: ', error));
};
```

When the user is signing in, he is on a login page which defined as a GuestGuard:

```
const GuestGuard = (props: GuestGuardProps) => {
  console.log('Guest Gard Triggered');
  const { children, fallback } = props;
  const router = useRouter();
  const auth = getAuth();
  const [user, loading] = useAuthState(auth);

  if (loading) return fallback;

  if (!!user) {
    router.replace('/');
    
return fallback;
  } else {
    return <>{children}</>;
  }
};
```

As soon as we get `user` object from firebase GuestGuard redirects to /home page which is defined as AuthGuard:

```
const AuthGuard = (props: AuthGuardProps) => {
  console.log('AuthGard triggered!');
  const { children } = props;
  const router = useRouter();
  const auth = getAuth();
  const [user, loading] = useAuthState(auth);
  const userMe = useUserMeQuery({ enabled: !!user });

  if (loading) return <FallbackSpinner message='Checking auth ...' />;

  if (!user) {
    router.replace('/login');
    
return <FallbackSpinner message='Redirecting to login page ...' />;
  } else if (!userMe.data?.data.role) {
    return <FallbackSpinner message='Getting user data ...' />;
  } else {
    return <>{children}</>;
  }
};
```

When `loading` is done and there is no user, AuthGuard will redirect to the /login page. 

Otherwise, it will start loading userMe with reactQuery which will be enabled with `!!user`. That is when /api/user/me will be fetched for the first time, but it is too soon as serverSideLogIn did not yet happen. Only Firebase login is happening at this point. 

The code is a bit messy and not optimized as I had to debug and understand why it is happening and now that I know why, I am not sure how to fix it. 

Basically instead of relying on `!!user` which belongs to Firebase for enabling userMe endpoint, I need to check the `user` object which belongs to this library and comes from /api/login.

Sorry, it is so long and I hope my problem makes more sense now.

Thanks!
Vitally

**Comment by Vitallyz** [comment]
Basically, I need to solve that: https://github.com/awinogrodzki/next-firebase-auth-edge/issues/106. This server-side auth provider will give me the server-side `user` when server-side authentication is done.

**Comment by awinogrodzki** [comment]
Just to add on this, react-firebase-hooks looks like you could provide a callback on `onAuthStateCange`.

```
The useAuthState hook takes the following parameters:

auth: auth.Auth instance for the app you would like to monitor
options: (optional) `Object with the following parameters:
onUserChanged: (optional) function to be called with auth.User each time the user changes. This allows you to do things like load custom claims.
```

You could call `/api/login` inside `onUserChanged`. If the latter is async, I can imagine you could keep those two users in sync.

But relying only on server-side user is not a bad idea either :-)

**Comment by awinogrodzki** [comment]
Hey @Vitallyz,

I will close the issue now to improve visibility of other issues. Let me know if you have any more questions :-)
