### ISSUE TITLE
Is it possible to use ServerAuthProvider wrapper with Next.js pages/ directory setup?

### ISSUE THREAD

**Issue by Vitallyz** [awinogrodzki/next-firebase-auth-edge#106]
Trying to use the ServerAuthProvider by wrapping some client-side components and getting this error: 

You're importing a component that needs next/headers. That only works in a Server Component which is not supported in the pages/ directory. Read more: https://nextjs.org/docs/getting-started/react-essentials#server-components

![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/85226925/cef868e6-914d-4ed9-9e86-299b680020b5)

I am using a template that has been set with pages/ directory. Not very familiar with the new Next.js way of using app/ directory as per the library examples. I am using the MaterialUI template that is using the old way of Next.js.

Is there a way to do what  ServerAuthProvider does with my old Next.js setup? 

Or should I spend some time converting to the new app/ directory way of Next.js?

Thanks!
Vitally

**Comment by awinogrodzki** [comment]
@Vitallyz in short, yes.

You could use `getTokensFromObject` inside `MyApp.getInitialProps` (https://nextjs.org/docs/pages/building-your-application/routing/custom-app) to fetch user token and then pass it down using context:

```tsx
export default function MyApp({
  Component,
  pageProps,
  user,
}: AppProps & AppOwnProps) {
  return (
    <AuthProvider defaultUser={user}>
      <p>Data: {example}</p>
      <Component {...pageProps} />
    </AuthProvider>
  )
}
 
MyApp.getInitialProps = async (
  context: AppContext
): Promise<AppOwnProps & AppInitialProps> => {
  const ctx = await App.getInitialProps(context);
  const tokens = await getTokensFromObject(req.cookies, {
    apiKey: "firebase-api-key",
    cookieName: "AuthToken",
    cookieSignatureKeys: ["secret1", "secret2"],
    serviceAccount: {
      projectId: "firebase-project-id",
      privateKey: "firebase service account private key",
      clientEmail: "firebase service account client email",
    },
  });
 
  return { ...ctx, user: toUser(tokens) }
}
```

**Comment by awinogrodzki** [comment]
I will close the issue now. Let me know if you have any more questions :-)

**Comment by Vitallyz** [comment]
Thanks! I could not get it to work. I will wait till the template I use will be upgraded to the App routes and will use the original async AuthProvider.
