### ISSUE TITLE
Using the library without a Service Account in an authenticated Google Cloud Run environment

### ISSUE THREAD

**Issue by Faridmurzone** [awinogrodzki/next-firebase-auth-edge#109]
Hello, I'm interested in using next-firebase-auth-edge for a project that runs on Google Cloud Run. Our security policy prohibits us from using API keys and explicitly loading Service Account credentials.

The problem is that the middleware currently requires a serviceAccount field with the following properties:
```
serviceAccount: {
    projectId: credentials.project_id,
    clientEmail: credentials.client_email,
    privateKey: credentials.private_key.replace(/\\n/g, '\n'),
}
```

Given that Cloud Run already provides an authenticated environment, is there a way to configure the middleware to use the existing authentication instead of requiring an explicit Service Account?

Thank you in advance for your time and assistance.

**Comment by awinogrodzki** [comment]
Hey @Faridmurzone,

That should be incredibly useful. I am looking at Firebase Admin internals and it seems there are multiple ways to get credentials from the environment. I am not sure which one is Cloud Run specific, so probably I'll need to setup some example project.

Do you know some useful examples to get me started quickly?

**Comment by seanaguinaga** [comment]
https://firebase.google.com/docs/hosting/frameworks/nextjs#optional_integrate_with_firebase_authentication

I know that you can get this when running on firebase functions

**Comment by awinogrodzki** [comment]
Hey @Faridmurzone,

Thank you for your patience. 

In `next-firebase-auth-edge@1.3.0` I introduced Google Cloud Run default service credentials support.

Key things to note:
- If you use `getFirebaseAuth`, you need to pass configuration object with empty `serviceAccount` option to indicate that the app should extract default credentials from the environment.
- You need to enable IAM Service Credentials API and make sure default service account has `iam.serviceAccounts.signBlob` permission

See [docs](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/cloud-run) for more information

You can find working starter example run in Google Cloud Run environment here: https://next13-typescript-starter-m2gwdqnpta-nw.a.run.app/
