### ISSUE TITLE
Always handleInvalidToken after deploying with firebase hosting

### ISSUE THREAD

**Issue by gmalagnini** [awinogrodzki/next-firebase-auth-edge#122]
Hi, i'm working on the "next13-typescript-starter" example project (the only changes I've made are the env variables in the .env.local file).
In a local environment everything works fine!
After deploying the app with the `firebase deploy` command, after logging in through the google sign in popup , the site keeps ending in **handleInvalidToken** callback.

There is a way to get a more detailed explanation of the problem?

Just to know, I setup the firebase hosting configurations after enabling this from the command line
`firebase experiments:enable webframeworks`

**Comment by awinogrodzki** [comment]
Hey @gmalagnini!

> There is a way to get a more detailed explanation of the problem?

I am working on debug mode that would help developers to figure out such cases. It should be ready in next patch version.

Until then, let's try to figure out the reason you're ending up in `handleInvalidToken`.

`handleInvalidToken` is called only in one case – when there are no credentials attached to the request.

Could you check if the request that's ending in `handleInvalidToken` has `Cookie` header with two authentication cookies, based on `cookieName` that you provided to `authentication` middleware function? Eg. If you passed `AuthToken` as `cookieName` those cookies should be named `AuthToken` and `AuthToken.sig`.

It seems like those cookies are missing

**Comment by gmalagnini** [comment]
> It seems like those cookies are missing

They were indeed! 
Thanks for the hint @awinogrodzki , the problem was related to the cookie name;
apparently the combination of firebase hosting + firebase functions don't allow to pass cookies named differently from "__session" (https://firebase.google.com/docs/hosting/manage-cache#using_cookies) so there's no chance to create a "__session.sig"  one! 😞 

There's a solution (maybe trying to unify both cookies in a single __session one and then split them in before calling the authentication() function, i don't know) or should i consider to deploy the app in a different platform?

**Comment by gmalagnini** [comment]
> (maybe trying to unify both cookies in a single __session one and then split them in before calling the authentication() function, i don't know)

I've just tried this option and - although it's pretty ugly - it works. 
@matthewlongpre 's answer in #19 really helped me out, basically i've just removed firebase operations from his implementation and saved directly both the idToken and refreshToken in the __session cookie
