### ISSUE TITLE
Change of user email leads to logout

### ISSUE THREAD

**Issue by alexeigs** [awinogrodzki/next-firebase-auth-edge#124]
I'm trying to update the user's email which currently leads to a `auth/user-token-expired` error if I call `auth.currentUser.getIdTokenResult(true)` on the client, after updating the email like:

```
const { updateUser } = getFirebaseAuth(authConfig.serviceAccount, authConfig.apiKey)

export type UpdateEmailRequest = {
  email: string
}

export async function POST(request: NextRequest) {
  const tokens = await getTokens(request.cookies, authConfig)
  if (!tokens) {
    throw new Error('Cannot refresh custom claims of unauthenticated user')
  }

  const { email } = (await request.json()) as UpdateEmailRequest
  await updateUser(tokens.decodedToken.uid, { email, emailVerified: false })

  const response = new NextResponse(null, {
    status: 200,
    headers: { 'content-type': 'application/json' },
  })

  // Attach `Set-Cookie` headers with token containing new custom claims
  await refreshAuthCookies(tokens.token, response, authConfig)

  return response
}
```

1. Can the auth-related email be changed without our user to be logged out? If yes, how can I achieve that?
2. If 1 can be achieved, is there a way to update the email with a server action instead of a post request or wouldn't that allow us to update the cookies as needed?

**Comment by awinogrodzki** [comment]
Hey @alexeigs! Great question. 

There is pretty good explanation for the issue you're having here: https://stackoverflow.com/questions/54522036/firebase-admin-auth-updateuser-causes-auth-user-token-expired

Basically, after every **significant change** to the user account (this includes email change), you need to ask user to re-authorize.

> If 1 can be achieved, is there a way to update the email with a server action instead of a post request or wouldn't that allow us to update the cookies as needed?

At this moment, Server Actions do not support response manipulation in any way. If we consider the architecture of Server Actions, I don't think it will be introduced soon. Best way to update the cookies after using Server Actions would be to call `/api/login` with fresh token again. Login endpoint works exactly as `refreshAuthCookies` without custom logic.


Let me know if this answered your question. Cheers!

**Comment by alexeigs** [comment]
Thanks for the reply. I guess I will just prompt the user to login again resp. send them a sign-in link in the case of an email change. There is no real alternative to that if I understood it correctly. 

Do we also need remove the auth cookies at this point? I ran into some invalid auth issues likely relating to invalid cookies previously; could this also happen here if we don't keep it in sync?

Lastly, is there a practical difference if I use this lib's `updateUser` vs. doing so directly through the firebase-admin sdk inside an api call/server action?

**Comment by awinogrodzki** [comment]
> Do we also need remove the auth cookies at this point? I ran into some invalid auth issues likely relating to invalid cookies previously; could this also happen here if we don't keep it in sync?

I presume yes, although it really depends on what you want to achieve. I assume that if you call `auth.currentUser.getIdTokenResult(true)` you want to display latest data related to the user, so the approach should be removing authentication cookies after user e-mail. You can use `removeAuthCookies` from `next-firebase-auth-edge/lib/next/cookies` to achieve this.

> Lastly, is there a practical difference if I use this lib's updateUser vs. doing so directly through the firebase-admin sdk inside an api call/server action?

No, those functions should work the same. `updateUser` can be used both in Edge and Node.js runtimes, but you can definitely use `firebase-admin` in API Routes run inside Node.js

**Comment by awinogrodzki** [comment]
I will close the issue now. If you have any further questions or thoughts, please let me know :-)
