### ISSUE TITLE
provide getUserByEmail method

### ISSUE THREAD

**Issue by GorvGoyl** [awinogrodzki/next-firebase-auth-edge#125]
Hi, Could you please also add a method to retrieve user by providing email id? It already exists in official firebase admin https://firebase.google.com/docs/auth/admin/manage-users#retrieve_user_data.

```
getAuth()
  .getUserByEmail(email)
  .then((userRecord) => {
    // See the UserRecord reference doc for the contents of userRecord.
    console.log(`Successfully fetched user data: ${userRecord.toJSON()}`);
  })
  .catch((error) => {
    console.log('Error fetching user data:', error);
  });
```

Thank you for building this library.

**Comment by awinogrodzki** [comment]
Hey @GorvGoyl! Thanks for a request.

I will include the method in upcoming changes.

**Comment by awinogrodzki** [comment]
Hello @GorvGoyl,

`getUserByEmail` method was introduced in `next-firebase-auth-edge@0.11.2`

Let me know if it works,
Cheers!
