### ISSUE TITLE
AppCheck Support

### ISSUE THREAD

**Issue by seanaguinaga** [awinogrodzki/next-firebase-auth-edge#127]
```bash
 ⨯ node_modules\next-firebase-auth-edge\lib\auth\index.js (47:14) @ customTokenToIdAndRefreshTokens
 ⨯ Problem getting a refresh token: {"error":{"code":401,"message":"Firebase App Check token is invalid.","errors":[{"message":"Firebase App Check token is invalid.","domain":"global","reason":"unauthorized"}],"status":"UNAUTHENTICATED"}}
null
```

Looks like AppCheck headers aren't being passed through?

[How to](https://firebase.google.com/docs/app-check/web/custom-resource)

[customTokenToIdAndRefreshTokens](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/846e94054bd1b4df7bb214786325dac6a8929019/src/auth/index.ts#L45)

**Comment by seanaguinaga** [comment]
Maybe because it is in beta technically there are no actual docs?

https://firebase.google.com/docs/reference/rest/auth

**Comment by awinogrodzki** [comment]
Hey @seanaguinaga! Thanks for reporting!

The library does not support AppCheck yet.

Simply passing `X-Firebase-AppCheck` header would not solve the problem.

A separate verification flow would have to be implemented as in this example: https://firebase.google.com/docs/app-check/custom-resource-backend

Basically, I would have to reverse-engineer the verification flow provided by ```tsx
import { getAppCheck } from "firebase-admin/app-check";
//...
await getAppCheck().verifyToken(appCheckToken)
```
and adapt it for edge runtimes.

Could you describe your use-case? What are you using AppCheck for?

**Comment by seanaguinaga** [comment]
You're right! My bad

Just to prevent account creation by bots (hopefully 🤞)

I will ask their support to see if it's just a param added to the url or passed in some other way via the REST API that you are using to get and refresh tokens in the custom middleware implementations

**Comment by awinogrodzki** [comment]
Hey @seanaguinaga! 

AppCheck seems like a vital function if we want to scale our apps in production environment. I will soon start to implement app check flow together with some examples.

**Comment by seanaguinaga** [comment]
Sorry no one from google got back to me yet!

Yeah it's very helpful for preventing all sorts of abuse! I visible recaptchas usually!

**Comment by awinogrodzki** [comment]
Hey @seanaguinaga!

App Check support was released in `next-firebase-auth-edge@0.11.0`.

Follow README for more info: https://github.com/awinogrodzki/next-firebase-auth-edge?tab=readme-ov-file#app-check-support

Let me know how it works for you :-)

**Comment by seanaguinaga** [comment]
😇 🤩 👏 

Upgrading now!

**Comment by seanaguinaga** [comment]
The trick of "proxying" app router API requests via the regular API routes was very clever! I do wonder if it will be be supported forever!

**Comment by awinogrodzki** [comment]
Thanks for the suggestion! I added improvement in https://github.com/awinogrodzki/next-firebase-auth-edge/commit/140ba4ace7181ab6ea363a56021cec30fe649f81

> Also, how the heck did you find the documentation for any of this in regards to their raw API routes? I'm impressed!

I used the best possible documentation – the code :D

I lookup https://github.com/firebase/firebase-admin-node implementation for details :)

Thanks!
