### ISSUE TITLE
Stucks at redirect

### ISSUE THREAD

**Issue by jsonkcli** [awinogrodzki/next-firebase-auth-edge#129]
This is not working for me and I'm not able to debug bc it seems to be happening internally, 
I realized two things, the router.push() doesnt trigger and  handleValidToken in the middleware, 
it's always hitting handleInvalidToken

issue #54 

this is what I see in the terminal -  
```⨯ "pkcs8" must be PKCS#8 formatted string
null

browser console  - Failed to load resource: the server responded with a status of 500 (Internal Server Error) - http://localhost:3000/api/login


These are my variables Idk what I may be missing 

FIREBASE_PROJECT_ID=""
FIREBASE_ADMIN_CLIENT_EMAIL=""

NEXT_PUBLIC_REDIRECT_URL="http://localhost:3000/auth/callback"
NEXT_PUBLIC_FIREBASE_API_KEY=""
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=""
NEXT_PUBLIC_FIREBASE_DATABASE_URL=""
NEXT_PUBLIC_FIREBASE_PROJECT_ID="a"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=""
```

Reproduce: Run the starter example
[examples/next13-typescript-starter](https://github.com/ensite-in/next-firebase-auth-edge/tree/main/examples/next13-typescript-starter)

**Comment by jsonkcli** [comment]
> This is not working for me and I'm not able to debug bc it seems to be happening internally, I realized two things, the router.push() doesnt trigger and handleValidToken in the middleware, it's always hitting handleInvalidToken
> 
> this is what I see in the terminal - ⨯ "pkcs8" must be PKCS#8 formatted string null
> 
> and this in the browser console - Failed to load resource: the server responded with a status of 500 (Internal Server Error) - http://localhost:3000/api/login
> 
> These are my variables Idk what I may be missing
> 
> FIREBASE_PROJECT_ID="" FIREBASE_ADMIN_CLIENT_EMAIL=""
> 
> NEXT_PUBLIC_REDIRECT_URL="http://localhost:3000/auth/callback" NEXT_PUBLIC_FIREBASE_API_KEY="" NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="" NEXT_PUBLIC_FIREBASE_DATABASE_URL="" NEXT_PUBLIC_FIREBASE_PROJECT_ID="a" NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=""

**Comment by awinogrodzki** [comment]
Hey @jsonkcli, thanks for reporting!

Does your `.env.local` file contain `FIREBASE_API_KEY` and `FIREBASE_ADMIN_PRIVATE_KEY` variables?

Have you assigned those variables with valid values based on https://github.com/awinogrodzki/next-firebase-auth-edge/tree/main/examples/next13-typescript-starter README?

**Comment by jsonkcli** [comment]
Thanks @awinogrodzki  it's working now.
The issue was I didn't put -----BEGIN PRIVATE KEY-----\{private-key}\n-----END PRIVATE KEY-----\n"

around the Private key

**Comment by jsonkcli** [comment]
Unrelated topic - How do I protect specific routes instead of the whole application. I have my landing page in app/page.ts and the rest of the app in (app)/. 

I don't want the landing page protected
