### ISSUE TITLE
Add support for node@20

### ISSUE THREAD

**Issue by MartinXPN** [awinogrodzki/next-firebase-auth-edge#130]
Vercel (as well as Firebase Functions) already supports `node@20`. It would be really great to add support for `node@20`. 
I'm currently trying to upgrade the node.js version (20.10.0 on my machine) but get an error:
```
error next-firebase-auth-edge@0.10.2: The engine "node" is incompatible with this module. Expected version ">=16.0.0 <20.0.0". Got "20.10.0"
error Found incompatible module.
```

**Comment by awinogrodzki** [comment]
Hey @MartinXPN!

Thanks for reporting.

Support for Node 20 was added in `next-firebase-auth-edge@0.11.1`

Let me know if that helps. Cheers 🎉
