### ISSUE TITLE
Do we need to manually call `api/login` inside `handleIdTokenChanged`?

### ISSUE THREAD

**Issue by abusada** [awinogrodzki/next-firebase-auth-edge#133]
Hello, I am not sure if i should call `/api/login` from inside `handleIdTokenChanged`, the reason i'm confused is because: 
1. Inside `/examples/next13-typescript-firebaseui/auth/client-auth-provider.tsx` you do call [`/api/login` ](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-firebaseui/auth/client-auth-provider.tsx#L28).
2. Inside `/examples/next13-typescript-starter/auth/client-auth-provider.tsx` you don't.
3. In readme's [AuthProvider](https://github.com/awinogrodzki/next-firebase-auth-edge?tab=readme-ov-file#authprovider) snippet, you don't!

What is the right / recommended behavior?

**Comment by awinogrodzki** [comment]
Hello @abusada,

Thanks for reaching out. That's a fair question.

There is no right behaviour – it should depend on your needs and use case. That said, I've recently started moving towards approach from `next13-typescript-starter` example.

In `next13-typescript-starter` we call `/api/login` just after using `signIn...` functions from official Firebase JS SDK: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/app/login/LoginPage.tsx#L51-L56

It seems `README.md` has outdated `AuthProvider` example. I will update the readme to avoid confusion. Thanks!
