### ISSUE TITLE
Authenticating via sendSignInLinkToEmail

### ISSUE THREAD

**Issue by dparrelli** [awinogrodzki/next-firebase-auth-edge#135]
Hey there! 

I've been playing around with your package and wanted to send a massive thank you for setting this up. It has been incredibly helpful and working great so far.

I was curious, is it possible to login/register users via [sendSignInLinkToEmail](https://firebase.google.com/docs/auth/web/email-link-auth), or would that not be possible just yet?

Thanks

**Comment by awinogrodzki** [comment]
Hey @dparrelli! I'm glad you find the library useful :-) 

I haven't yet integrated with [sendSignInLinkToEmail](https://firebase.google.com/docs/auth/web/email-link-auth), but it sounds like a quite useful feature.

I will take this on as a next feature.

**Comment by dparrelli** [comment]
@awinogrodzki oh that's great to hear :) No doubt a lot of people will get value out of it since it's quite a popular form of auth these days. Looking forward to seeing what you come up with!

**Comment by awinogrodzki** [comment]
Hey @dparrelli!

I added `sendSignInLinkToEmail` support in `next-firebase-auth-edge@1.0.0` starter example https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/app/login/LoginPage.tsx#L47-L90

You can test it in starter demo https://next-firebase-auth-edge-starter.vercel.app/

**Comment by dparrelli** [comment]
Amazing work @awinogrodzki! Thanks so much for implementing that feature 🙌
