### ISSUE TITLE
Congratulations on 1.0!? 

### ISSUE THREAD

**Issue by seanaguinaga** [awinogrodzki/next-firebase-auth-edge#139]
I just ran my weekly package updates and saw a 1.0.0 after this!?

How amazing!

**Comment by awinogrodzki** [comment]
Thank you so much @seanaguinaga!

With 1.0 I did improve APIs and added some helper functions such as `redirectToHome` or `redirectToLoginPage`.

But the biggest feature is completely new, dedicated documentation page. https://next-firebase-auth-edge-docs.vercel.app/

🎉

**Comment by suntudo** [comment]
This all looks fantastic - thanks for all your work on this package!!
