### ISSUE TITLE
Cookie verification

### ISSUE THREAD

**Issue by itsWindows11** [awinogrodzki/next-firebase-auth-edge#141]
In this library, there's no way to verify a session cookie, compared to `firebase-admin` which has a `verifySessionCookie` function. Passing a cookie value generated from `firebase-admin`'s `createSessionCookie` to `verifyIdToken` leads to this error:
```js
{"code":"INVALID_ARGUMENT","message":"Invalid argument: idToken has incorrect \"iss\" (issuer) claim. Expected https://securetoken.google.com/***, but got https://session.firebase.google.com/***"}
```

**Comment by awinogrodzki** [comment]
Hey @itsWindows11! 

The library does not work with Firebase's `createSessionCookie` and `verifySessionCookie`. Could you explain your use case a bit? Why are you using those two functions? `authMiddleware` is responsible for creating and verifying session cookie, so the developer does not have to call those functions. You can still use `firebase-admin`'s `verifyIdToken` to verify the token returned from `getTokens` function
