### ISSUE TITLE
Is it necessary to invoke window.location.reload() as part of the logout process?

### ISSUE THREAD

**Issue by zameerejaz** [awinogrodzki/next-firebase-auth-edge#144]
I've implemented functionality to allow only verified emails to register. However, I'm encountering a problem when a user attempts to log in without verifying their email: an error correctly indicates that email verification is needed, but if I navigate back to the landing page, the header incorrectly displays as if I'm logged in. This issue persists until I manually refresh the page. The users can also navigate view pages that currently checks the tokens in the getServerSideProps 

` if (userCredential.user.emailVerified === false) {
          setEmailVerified(false);
          await signOut(auth);
          await logout();
          throw new Error("Please verify your email address");`
          
Any ideas on how to overcome this as i would like to show the error to the user and if i were to run a `winow.location.reload()` then the user may not see the error in time. 

I am using NextJs 14 (Pages Directory ) 
 
 
 Thanks all :)

**Comment by awinogrodzki** [comment]
Hey @zameerejaz!

What `/api/logout` call does is simply removing authenticated cookies, so any subsequent api request or page refresh would not have user credentials attached. 

In starter example, `window.location.reload()` is called simply to redirect user to login page using middleware.

You definitely could implement logout without having to reload the page. 

If you're header is showing as if user was loaded, you need to work on the underlying state. Eg. in recent starter example, `user` object is set to `null` after they sign out:

```tsx
  const handleIdTokenChanged = async (firebaseUser: FirebaseUser | null) => {
    if (firebaseUser) {
      const tokenResult = await firebaseUser.getIdTokenResult();

      await login(tokenResult.token);
      setUser(toUser(firebaseUser, tokenResult));
      return;
    }

    await logout();
    setUser(null);
  };
```

Let me know if that helps 🌮

**Comment by zameerejaz** [comment]
Thank youuu, ill give it a go :)

**Comment by awinogrodzki** [comment]
I will now close the issue. Feel free to reopen if you still have issues with logout :-)
