### ISSUE TITLE
Getting invalid token in incognito mode and firefox

### ISSUE THREAD

**Issue by kucho** [awinogrodzki/next-firebase-auth-edge#145]
Hi! I am working on a greenfield nextjs project and recently deployed to vercel. Everything was working fine until yesterday, when I changed browsers (for fun) and noticed I am always hitting `handleInvalidToken` in incognito mode and firefox related browsers. 

I am unsure how to debug it. I am happy to help getting this fixed!

**Comment by tstpierre** [comment]
I'm having the same issue - out of the blue.  I even have a branch that was deployed a few weeks ago that is still working - but the latest npm is always falling into handleInvalidToken (and there's no context to log at that point).

The only thing I've noticed is that my (working) branch writes two session cookies on a successful login: `CookieName` + `CookieName.sig`.  The (failing) current code is only writing the first cookie and not the `.sig`

**Comment by merrellj-codeup** [comment]
My unresolved issue I created yesterday might be related: #146 

It's working in local, but the authentication flow is falling in handleInvalidToken in the firebase deployment environment.

**Comment by tstpierre** [comment]
@awinogrodzki Any thoughts on why the signed cookie is not being written?

Looking at the code (https://github.com/awinogrodzki/next-firebase-auth-edge/blob/926f23656e1fd935d064cb360e424597d80431af/src/auth/cookies/index.ts#L1) it seems like this is failing to be set.  But I'm not sure why a cookie IS being set without the `.sig`

**Comment by awinogrodzki** [comment]
Hey @kucho,

Thanks for reporting the issue. Could you share a link to your Vercel environment, as well as output of `npx next info`?

Also, are you on Windows or Mac? 

Could you also test this issue on https://next-firebase-auth-edge-starter.vercel.app/ and let me know if it's reproducible?

**Comment by awinogrodzki** [comment]
I am testing https://next-firebase-auth-edge-starter.vercel.app on number of browsers (Chrome, Firefox, Opera, Safari, Edge) in and out incognito mode and cannot reproduce the issue on my side, so it might be related with a configuration.

BTW. could you also share your middleware.ts (without credentials) :-)

**Comment by kucho** [comment]
@awinogrodzki I can not reproduce the error on the demo page.

I have tried:
- Upgrade nextjs
- Upgrade next-firebase-auth-edge 
- Disabled preview secure auth cookies
- Disabled vercel preview protection

Still getting 

<img width="1039" alt="image" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/26698519/7a6b759a-a772-46cd-b2bc-a893c6fb4da3">


I am using mac. The `npx next info` output is:

```

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 21.4.0
  npm: 10.2.5
  Yarn: 1.22.21
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.1-canary.51 // Latest available version is detected (14.1.1-canary.51).
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

The `middleware.ts`:

```ts
import { authMiddleware, redirectToHome, redirectToLogin } from "next-firebase-auth-edge";
import { NextRequest, NextResponse } from "next/server";
import { env } from "~/env";

const AUTH_PATHS = ["/login"];

export async function middleware(request: NextRequest) {
	return authMiddleware(request, {
		loginPath: "/api/login",
		logoutPath: "/api/logout",
		apiKey: env.FIREBASE_API_KEY,
		cookieName: "AuthToken",
		cookieSignatureKeys: ["secret1", "secret2"],
		cookieSerializeOptions: {
			path: "/",
			httpOnly: true,
			secure: env.SECURE_AUTH_COOKIE,
			sameSite: "lax" as const,
			maxAge: 7 * 60 * 60 * 24, // 7 days
		},
		serviceAccount: {
			projectId: env.FIREBASE_PROJECT_ID,
			clientEmail: env.FIREBASE_CLIENT_EMAIL,
			privateKey: env.FIREBASE_PRIVATE_KEY,
		},
		handleValidToken: async ({ token, decodedToken }, headers) => {
			if (AUTH_PATHS.includes(request.nextUrl.pathname)) {
				return redirectToHome(request);
			}

			return NextResponse.next({
				request: {
					headers,
				},
			});
		},
		handleInvalidToken: async () => {
			console.warn("Invalid firebase token");

			return redirectToLogin(request, {
				path: "/login",
				publicPaths: AUTH_PATHS,
			});
		},
		handleError: async (error) => {
			console.error("Unhandled authentication error", { error });
			return redirectToLogin(request, {
				path: "/login",
				publicPaths: AUTH_PATHS,
			});
		},
	});
}

export const config = {
	matcher: ["/api/login", "/api/logout", "/login", "/logout"],
};

```

**Comment by tstpierre** [comment]
My middleware:

`import { NextRequest, NextResponse } from "next/server";
import { authMiddleware, redirectToHome, redirectToLogin } from "next-firebase-auth-edge/";

import { authConfig } from "@/lib/auth2/config/server.config";

const ANON_PATHS = ["/account/signin", "/account/create", "/account/reset"];
const PUBLIC_PATHS = [...ANON_PATHS, "/monitoring"];

export async function middleware(request: NextRequest) {
    return authMiddleware(request, {
        loginPath: "/api/account/signin",
        logoutPath: "/api/account/signout",
        apiKey: authConfig.apiKey,
        cookieName: authConfig.cookieName,
        cookieSerializeOptions: authConfig.cookieSerializeOptions,
        cookieSignatureKeys: authConfig.cookieSignatureKeys,
        serviceAccount: authConfig.serviceAccount,

        handleValidToken: async ({ token, decodedToken }, headers) => {
            if (ANON_PATHS.includes(request.nextUrl.pathname)) {
                return redirectToHome(request);
            }

            return NextResponse.next({
                request: {
                    headers,
                },
            });
        },

        handleInvalidToken: async () => {
            console.log("Server Config", authConfig);
            console.log("Invalid token");

            return redirectToLogin(request, {
                path: "/account/signin",
                publicPaths: PUBLIC_PATHS,
            });
        },

        handleError: async (error) => {
            return redirectToLogin(request);
        },
    });
}

export const config = {
    matcher: [
        "/", // Match all paths
        "/((?!_next|favicon.ico|api|.*\\.).*)", // Matches all paths except /_next, /favicon.ico, /api, and files with extension
        "/api/account/signin", // This API endpoint is not protected by authMiddleware
        "/api/account/signout", // This API endpoint is not protected by authMiddleware
    ],
};
`

**Comment by awinogrodzki** [comment]
@kucho,

I am trying to login to https://portal-nextjs-git-eng-401-ridepanda.vercel.app/ via email link. I receive e-mail as expected, but application fails to process my login, when I click on the link.

Could you copy the contents of your login page? I am interested mainly in `signInWithEmailLink` call, which seems not to be occurring.

In starter example, `signInWithEmailLink` is handler here: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/app/login/LoginPage.tsx#L68-L93

If you open dev console in starter example and follow the email link, eventually you'll see a call to `https://identitytoolkit.googleapis.com/v1/accounts:signInWithEmailLink?key=XXX`, which does not occur in portal-nextjs-git-eng-401-ridepanda.vercel.app

**Comment by kucho** [comment]
I still don't have a proper explanation to what happened with my early deployment that succeeded on chromium, but failed on firefox. I made a bunch of changes, added and removed a lot of bits, and this time around I missed the `signInWithEmailLink` call.

After handling it like in your example, it just worked. I think I assumed (incorrectly) the login params were being handled by the middleware and the redirection was all happening at this level, not client side.

Thank you for your help and  patient 🙏! Feel free to close this issue.

**Comment by awinogrodzki** [comment]
I'm glad to hear that! 

If anything else comes up, don't hesitate to create another issue. 

Cheers 🎉
