### ISSUE TITLE
Cookie expiration

### ISSUE THREAD

**Issue by 27lakshay** [awinogrodzki/next-firebase-auth-edge#151]
Hey @awinogrodzki 
Thank you so much for this amazing library.

I wanted to know how can I keep my user indefinitely logged in/their cookie never expires.

**Comment by awinogrodzki** [comment]
Hey @27lakshay!

The process of verifying user token requires valid public certificates fetched from Google, which have expiry date. See [Verify ID tokens using a third-party JWT library](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library)

> Finally, ensure that the ID token was signed by the private key corresponding to the token's kid claim. Grab the public key from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com and use a JWT library to verify the signature. Use the value of max-age in the Cache-Control header of the response from that endpoint to know when to refresh the public keys.


To work around this issue, we theoretically could store expired certificates to validate against, but this would be potential security risk. 

This limitation also exists in `firebase-admin-node` and other libraries that implement Firebase Authentication, unless they allow some undocumented behaviour.

Either way, I will experiment with Google APIs to see if we can achieve endless session using token refresh. I am not sure yet if token refresh should will also refresh `kid` identifier that corresponds to valid certificates.

I will let you know later today

**Comment by awinogrodzki** [comment]
Here's a good conversation about this issue: https://stackoverflow.com/questions/70350163/firebase-expired-idtoken-becoming-invalid-after-1-week

`kid` header is being refreshed together with the rest of the token, so it might be we can refresh the token after `kid` has expired.

I will prepare some experimental release where we could potentially test this

**Comment by awinogrodzki** [comment]
@27lakshay, I've prepared experimental `next-firebase-auth-edge@1.3.1-unstable.1` package. 

You can add `UNSAFE_expireTokenOnInvalidKidHeader: true` to options passed to `authMiddleware`, `getTokens` and `getFirebaseAuth` functions.

`UNSAFE_expireTokenOnInvalidKidHeader` instructs token verifier to throw `TOKEN_EXPIRED` error instead of `INVALID_ARGUMENT` or `INVALID_SIGNATURE` error, which causes token to be refreshed.

Please note that there is a chance that token refresh will fail after Google certificates are refreshed. If that chance is 100%, you would not be able to implement endless loading. 

Please give it a try and let me know if it extended your session's lifetime.

**Comment by 27lakshay** [comment]
Hi @awinogrodzki ,
Thank you so much for such a quick response and explanation.

I would like to explain my usecase, right now I am using firebase client sdk for auth in nextjs, as currently auth is client based I cannot do SSR for certain pages and also I have to show loader on login/register page and then redirect the user if they are signed in as per firebase client sdk.
I need my users to be indefinitely logged in, until and unless we delete or explicitly revoke their tokens, now this works successfully with firebase client sdk and the user never gets signed out but the SSR part is not possible with this.
I tried to build a rough implementation with next-firebase-auth-edge, it works great, its fast, works well with next-intl, perfect for my usecase but,
if the cookie gets expired it just runs the callback handleInvalidToken in middleware and doesn't provide any information about why it was invalid, if it could throw something like TOKEN_EXPIRED or some other unique identifier which helps the client code understand that the certificate got expired, then I could just show a loader on client for this particular case and hit the auth/login endpoint again from onAuthStateChanged once the firebase auth is intialized on client.
Same thing for the google certificates part, if the authMiddleware could throw that google certificates got expired then I could hit the api/login again as per the firebase client auth state.
Any other potentials solutions are also welcome.

**Comment by awinogrodzki** [comment]
Actually, other developers also requested `handleInvalidToken` to provide more insight to the reason behind token being invalid.

I've just released `next-firebase-auth-edge@1.4.0`

Since `1.4.0`, `handleInvalidToken` is now called with `InvalidTokenReason` as the first argument.

```tsx
export enum InvalidTokenReason {
  MISSING_CREDENTIALS = 'MISSING_CREDENTIALS',
  MISSING_REFRESH_TOKEN = 'MISSING_REFRESH_TOKEN',
  MALFORMED_CREDENTIALS = 'MALFORMED_CREDENTIALS',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
}

const InvalidTokenMessages: Record<InvalidTokenReason, string> = {
  [InvalidTokenReason.MISSING_CREDENTIALS]: 'Missing credentials',
  [InvalidTokenReason.MALFORMED_CREDENTIALS]: 'Credentials are incorrectly formatted',
  [InvalidTokenReason.INVALID_SIGNATURE]: 'Credentials have invalid signature',
  [InvalidTokenReason.MISSING_REFRESH_TOKEN]: 'Refresh token is missing',
  [InvalidTokenReason.INVALID_CREDENTIALS]: 'Invalid credentials'
};
```

Please remember that `handleInvalidToken` is mostly informative and most of the time, the reason would be `InvalidTokenReason.MISSING_CREDENTIALS`.

**Comment by awinogrodzki** [comment]
As for `TOKEN_EXPIRED` error – the library does not throw this error explicitly. `TOKEN_EXPIRED` error is catched internally to trigger token refresh. If token refresh fails, the library calls `handleError` with `INVALID_CREDENTIAL` error. 

I've added some documentation on possible `AuthError` and `InvalidTokenReason` types. See https://next-firebase-auth-edge-docs.vercel.app/docs/errors 

Let me know if it helps

**Comment by awinogrodzki** [comment]
I will close the issue now, as it seems resolved. Cheers 🌮
