### ISSUE TITLE
cookieSignatureKeys configuration

### ISSUE THREAD

**Issue by FacundoRaviolo** [awinogrodzki/next-firebase-auth-edge#154]
Hello, everyone.

This is not an issue, but I'm not sure about where I should ask this. I'm a little bit lost.

It's about `cookieSignatureKeys`, in the examples I've seen always an array of two strings "secret1" and "secret2" in server config, but...
what kind of secret should I create, how and how many? I cannot use env variables, right? Because keys are used by middleware and it's not running into a NodeJS environment.

But if I have to add them in the source code, it's not a bad practice?

Sorry for the issue and I'll be waiting for anyone who can help me.
Thank you so much!!

PD: is it ok to open an issue for these questions, or should I avoid this?

**Comment by FacundoRaviolo** [comment]
Update: I just see that in the example project, middleware uses env variables, so I think I can use env variables to set secrets, right? I thought it could only be used in a NodeJS environment, but I think I was wrong.

But, I still want to know how many secrets I have to create and what kind of secrets? And with what tool could I do that?

Thanks!

**Comment by awinogrodzki** [comment]
> PD: is it ok to open an issue for these questions, or should I avoid this?

I more than encourage you to ask those questions here :-) A lot of users would search for an answer, but refrain to create an issue if they don't find one. Asking questions will help you and other people looking for similar answer, so it's more than okay to ask them. Thanks!

**Comment by FacundoRaviolo** [comment]
Thank you so much, Amadeusz! Your explanation was perfect. I completely understand the importance of keys and how I can use them.

Now, I was thinking of asking another question about something I observed in my tests with this library. However, now that you mentioned that _any cookie signed with the latter will be considered invalid and user will be forced to login page_, I think this is a good opportunity to ask.

Let's suppose a cookie is removed (due to expiration, for example, or because the previous cookie signature key was deleted). If a user enters the web, initially the cookie won't be there. However, the `onIdTokenChange` method will be automatically executed, setting the cookies again, and the user will remain logged in. However, the user might find a weird situation because when they initially enter the page, the middleware checks cookies and redirects to the login page. Then, the client component reads the Firebase token (since it's still present) and sets the cookie again without requiring a login.

Is there, maybe, a way to also remove the Firebase token in storage when a cookie is removed (I mean, just if I should do something like that and I'm not currently doing it, I don't want to overthink these situation), or something similar? Or is this behavior acceptable? What's the correct approach in this scenario?

My primary concern revolves around user experience. It would be akward to user to be redirected to the login page only to discover that the user is still logged in... Am I mistaken?

I'm not sure if I've explained this very well. Please let me know if I haven't. My apologies, my English is not the best 😬.

**Comment by awinogrodzki** [comment]
@FacundoRaviolo

When user cookies expire, but firebase is still logged-in using browser storage, user will be redirected to `/login` page, just to be redirected back to desired page. This is how *starter example* works, where this kind of flow is expected. 

The solution I see here is changing default [Authentication State Persistence] in Firebase Client – https://firebase.google.com/docs/auth/web/auth-state-persistence to `inMemoryPersistence`, but you would have to deviate from original example a bit and call `/api/login` and `/api/logut` outside of `AuthProvider`

I actually added an issue on this couple weeks back to explore this topic: https://github.com/awinogrodzki/next-firebase-auth-edge/issues/143

**Comment by FacundoRaviolo** [comment]
Thank you so much again!

I now understand.
Yeah, in the meanwhile my app can works like _starter example_. It's weird to be redirected to login and back again but it's something that happens a few times.

About the topic, I will think about it and try when I can.
But that's it. I just wanted to check if I was wrong.

Thank you, again, these answers were perfect.
And also thank you so much for this awesome library!
