### ISSUE TITLE
Works fine locally but cookies are not attached in Vercel deploy

### ISSUE THREAD

**Issue by bhaktatejas922** [awinogrodzki/next-firebase-auth-edge#162]
Been trying various things for days and could not find a solution. 

Can't get this to work on a vercel deploy (https) 

```
export const serverConfig = {
  useSecureCookies: 'false',
  firebaseApiKey: process.env.FIREBASE_ADMIN_API_KEY!,
  serviceAccount: process.env.FIREBASE_ADMIN_PRIVATE_KEY
    ? {
        projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, '\n')!
      }
    : undefined
}

export const authConfig = {
  apiKey: serverConfig.firebaseApiKey,
  cookieName: 'accessToken',
  cookieSignatureKeys: [process.env.COOKIE_SECRET_KEY_1!, process.env.COOKIE_SECRET_KEY_2!],
  cookieSerializeOptions: {
    path: '/',
    // httpOnly: true,
    secure: serverConfig.useSecureCookies, // Set this to true on HTTPS environments
    sameSite: 'lax' as const,
    maxAge: 12 * 60 * 60 * 24 // twelve days
  },
  serviceAccount: serverConfig.serviceAccount
}

export const serverConfig = {
  useSecureCookies: 'false',
  firebaseApiKey: process.env.FIREBASE_ADMIN_API_KEY!,
  serviceAccount: process.env.FIREBASE_ADMIN_PRIVATE_KEY
    ? {
        projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, '\n')!
      }
    : undefined
}

export const authConfig = {
  apiKey: serverConfig.firebaseApiKey,
  cookieName: 'accessToken',
  cookieSignatureKeys: [process.env.COOKIE_SECRET_KEY_1!, process.env.COOKIE_SECRET_KEY_2!],
  cookieSerializeOptions: {
    path: '/',
    // httpOnly: true,
    secure: serverConfig.useSecureCookies, // Set this to true on HTTPS environments
    sameSite: 'lax' as const,
    maxAge: 12 * 60 * 60 * 24 // twelve days
  },
  serviceAccount: serverConfig.serviceAccount
}
```

**Comment by bhaktatejas922** [comment]
Im not seeing any cookies sent with requests on vercel deploys, hence I get MISSING_CREDENTIALS errors on everything. closely examined the example and I'm following it closely. no idea what it could be

**Comment by bhaktatejas922** [comment]
Is there some URL we would need to configure in Vercel for this to work? Been stuck for days and going insane

**Comment by awinogrodzki** [comment]
Hello @bhaktatejas922!

Thanks for the question!

First of all, you can simplify your `serverConfig` to this:

```tsx
export const serverConfig = {
  useSecureCookies: 'false',
  firebaseApiKey: process.env.FIREBASE_ADMIN_API_KEY!,
  serviceAccount: {
        projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, '\n')!
   }
}
``` 

Example uses ternary operator for `serviceAccount` to run both in `Vercel` and `Google Cloud Run`. If you're planning to run the app in `Vercel`, `serviceAccount` is required, so you need to make sure `FIREBASE_ADMIN_*` variables are present in Vercel environment. I assume it is the case.

I see that you're passing `useSecureCookies: 'false'`. Vercel uses `https` by default, so you need to make sure to pass `true` instead of `false`. You can do this by introducing a separate environment variable and set it to `true` in Vercel:

```tsx
export const serverConfig = {
  useSecureCookies: process.env.USE_SECURE_COOKIES ?? 'false',
  firebaseApiKey: process.env.FIREBASE_ADMIN_API_KEY!,
  serviceAccount: {
        projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, '\n')!
   }
}
```

Let me know if this works :-)

**Comment by bhaktatejas922** [comment]
variables are all set, tried this already unfortunately. Seems to be a vercel issue I think? Not sure how you got your example to work then. Switched to aws amplify and it worked

**Comment by followbl** [comment]
are you mobile @bhaktatejas922 ?

**Comment by followbl** [comment]
@awinogrodzki beautiful library and excellent documentation on this.

I've got it working near perfectly in our app outside of the known firebase issues on getting `signInWithRedirect` to work. Have you had any success getting this to work within the app.

I've attempted a couple solutions...

first I attempted to proxy the requests through an auth subdomain, this is just on a standalone, vercel redirect on the domain like so...

vercel.json
```json
{
    "rewrites": [
        {
            "source": "/__/auth/(.*)",
            "destination": "https://${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}/__/auth/$1"
        },
        {
            "source": "/__/firebase/init.json",
            "destination": "${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}/__/firebase/init.json"
        }
    ]
}
```

did not work, it's mainly the request handler @ /auth `/__/auth/handler`

second attempt was to put it straight in the `next.config.js`

like so...

```js
const nextConfig ={
  async rewrites() {
    return [
      {
        source: "/__/auth/:path*",
        destination: `https://${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}.firebaseapp.com/__/auth/:path*`,
      },
    ];
  },
```

didn't work there. about to give up and go straight with the popups, but wanted to know if anyone has had any luck getting the `signInWithRedirect` to work with vercel.

thanks again for any tips, great library.

**Comment by awinogrodzki** [comment]
Hey @followbl! Thanks for reporting. Would you mind creating a separate issue for this? I haven't yet tested `signInWithRedirect` within Vercel. I will test it out the following week

**Comment by awinogrodzki** [comment]
It seems you are using browser other than Chrome.

The issue is mentioned in official docs: https://firebase.google.com/docs/auth/web/redirect-best-practices#overview

You should setup reverse proxy for `/__/auth`. Supposably you can achieve this with Vercel using `rewrites` https://vercel.com/guides/vercel-reverse-proxy-rewrites-external but I haven't tested that yet.

I will test it shortly. In the meantime, please create a separate issue if you wish to track development on this

**Comment by awinogrodzki** [comment]
I was able to make it work in all browsers with following steps:

1. Update `authDomain` firebase client setting to your own domain (in my case it's `next-firebase-auth-edge-starter.vercel.app`)
2. Update Google Cloud O-Auth 2.0 here: https://console.cloud.google.com/apis/credentials and with your custom domain
3. Exclude `/__/auth*` and `/__/firebase*` from Middleware matcher: as in https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next-typescript-starter/middleware.ts#L53
4. Update `next.config.js` with following `rewrites`: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next-typescript-starter/next.config.js#L7-L18

**Comment by JeromeDeLeon** [comment]
I'm having the same issue and would like to know what exactly you did on step 2. 😭 

For instance,

![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/32805276/ba66bb26-f01a-4caf-b7fe-6e3a134eb268)

For Authorized JS Origins, did you add `https://next-firebase-auth-edge-starter.vercel.app`?
For Authorized redirect URI, did you also add `https://next-firebase-auth-edge-starter.vercel.app/__/auth/handler`?

Like do I need to supply both of them? How long did it take for it to take effect?

I have mine set up on the Vercel preview environment and tested it on iOS 17 Safari, but for some reason, even after following everything, nothing happened after I got redirected back from Google.

```js
await getRedirectResult(auth); // always null 🤷🏼 
```

**Comment by awinogrodzki** [comment]
Here's OAuth 2.0 configuration for https://next-firebase-auth-edge-starter.vercel.app

<img width="504" alt="Screenshot 2024-05-27 at 09 13 21" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/12574743/1a3f169a-0eef-427c-b100-66308f49fa04">
