### ISSUE TITLE
[Question] How to use this lib with "Remember me" feature

### ISSUE THREAD

**Issue by JeromeDeLeon** [awinogrodzki/next-firebase-auth-edge#167]
This library is the one I'm considering using for our application and one of the things I'm looking for among other things like using this with the magic link, custom reset password link, etc. is implementing a "Remember me" feature.

With the `firebase/auth` client, we can do this via session storage persistent, but with this lib, how would you achieve some similar functionality? It doesn't have to be exactly like that but my thought initially was not to have an expiration date since cookies without an expiration date will automatically be deleted as soon as the user closes the browser. The only issue is that expiration has to be defined as part of this lib's configuration. 💭

**Comment by awinogrodzki** [comment]
Hey @JeromeDeLeon,

Great question.

According to [Web HTTP Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie) docs, if `Set-Cookie` header does not contain `Max-Age` or `Expires` attribute, it will expire when session ends.

You could achieve "Remember me" functionality by changing session cookie configuration based on some boolean value, as in following example:

```tsx
export async function middleware(request: NextRequest) {
  const rememberMe = request.headers.get('x-remember-me') === 'true';

  return authMiddleware(request, {
    ...
    cookieSerializeOptions: {
      path: '/',
      httpOnly: true,
      secure: true, // Set this to true on HTTPS environments
      sameSite: 'lax' as const,
      maxAge: rememberMe ? 12 * 60 * 60 * 24 : undefined 
    },
    ...
  });
}
```

**Comment by awinogrodzki** [comment]
I will close the issue now. Feel free to reopen if you have any further questions. Cheers 🎉
