### ISSUE TITLE
/api/login endpoint returns an error when accessed directly

### ISSUE THREAD

**Issue by AzuKi9140** [awinogrodzki/next-firebase-auth-edge#172]
**Summary:**
When directly accessing the `/api/login` endpoint on the publicly available Next Firebase Auth Edge demo site at [URL](https://next-firebase-auth-edge-starter.vercel.app/api/login), an error is encountered. The error message states: "This Edge Function has crashed. Your connection is working correctly. Vercel is working correctly." However, the `/api/logout` endpoint works as expected when accessed directly, and the `/api/login` endpoint functions properly when called from within the `/register` route.

**Steps to Reproduce:**
1. Visit the Next Firebase Auth Edge demo site at [URL](https://next-firebase-auth-edge-starter.vercel.app).
2. Directly access the `/api/login` endpoint by appending it to the base URL.
3. Observe the error message as shown in the attached screenshot.

**Expected Behavior:**
Clarification is needed on whether the error encountered when directly accessing the `/api/login` endpoint is an intended behavior or if it indicates an issue with the implementation.

**Actual Behavior:**
The `/api/login` endpoint returns an error message stating "This Edge Function has crashed. Your connection is working correctly. Vercel is working correctly." when accessed directly.

**Additional Information:**
- The `/api/logout` endpoint works as expected when accessed directly.
- The `/api/login` endpoint seems to function properly when called from within the `/register` route.
- When running the application locally and accessing the `/api/login` endpoint, the following error is encountered:
  ```
  ⨯ node_modules\jose\dist\browser\util\decode_protected_header.js (32:14) @ decodeProtectedHeader
  ⨯ Invalid Token or Protected Header formatting
  null
  ```
- I am a beginner learning Next.js, so I apologize if my question is misguided.

**Screenshot:**
![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/132641113/d5a969c3-d5f9-476c-849e-99a80445469f)

If you need any further information or clarification, please let me know. Thank you for your time and assistance in understanding this behavior.

Best regards!!

**Comment by awinogrodzki** [comment]
Hey @AzuKi9140!

Thanks for reporting.

In https://github.com/awinogrodzki/next-firebase-auth-edge/releases/tag/v1.4.5 I've released fix for this issue. Now, if `/api/login` is called directly (without appropriate headers), the middleware will return `400 Bad Request` response with following JSON content:
```json
{"success":false,"message":"Missing token"}
```

**Comment by AzuKi9140** [comment]
Thank you for fixing this! It was very helpful. I look forward to seeing more of your great work in the future.
