### ISSUE TITLE
[Cloudflare Pages] The 'cache' field on 'RequestInitializerDict' is not implemented.

### ISSUE THREAD

**Issue by samiy803** [awinogrodzki/next-firebase-auth-edge#173]
On certain edge runtimes like Cloudflare (possibly others too), `fetch()` doesn't implement the `cache` field. As such, it produces an error:
```
// POST https://redacted.pages.dev/api/login
  "logs": [
    {
      "message": [
        {
          "code": "INTERNAL_ERROR",
          "message": "Internal error: The 'cache' field on 'RequestInitializerDict' is not implemented."
        }
      ],
      "level": "error",
      "timestamp": 1715189441063
    }
  ],
```

See: https://github.com/cloudflare/workerd/issues/698

**Comment by samiy803** [comment]
Temporarily, can we add the feature to pass a custom `fetch()` function? Similar to: https://github.com/cloudflare/workerd/issues/698#issuecomment-2027798656

**Comment by tstpierre** [comment]
Linking this PR thats in flight by James for next-on-pages https://github.com/cloudflare/next-on-pages/pull/771

**Comment by awinogrodzki** [comment]
Hey! 

Thanks for reporting @samiy803.

I've released a fix/workaround in `next-firebase-auth-edge@1.5.0-canary.2`

More details about 1.5 can be found in https://github.com/awinogrodzki/next-firebase-auth-edge/pull/186

Could you test it and let me know if it works?

**Comment by asaroukou** [comment]
Hi @awinogrodzki, I have a question about this update. Does it revert the changes required for this issue to be fixed https://github.com/awinogrodzki/next-firebase-auth-edge/issues/159. We didn't bumped the lib to the last version yet 😄.

**Comment by awinogrodzki** [comment]
Hey @asaroukou, 

Yes, I've described the issue in this PR: https://github.com/awinogrodzki/next-firebase-auth-edge/pull/187

> This PR removes the usages of cache fetch option
> 
> Due to above, it's recommended to update Next.js to v14 along with the upgrade to next-firebase-auth-edge@1.5 to avoid caching issues

You need to update Next.js to version 14 before updating `next-firebase-auth-edge` to 1.5

**Comment by asaroukou** [comment]
> You need to update Next.js to version 14 before updating `next-firebase-auth-edge` to 1.5

Ok so if I understand correctly the caching issue was only related to next 13. Since we already have the 14.x installed it should be fine to bump the lib to his last version.

**Comment by awinogrodzki** [comment]
> Ok so if I understand correctly the caching issue was only related to next 13. Since we already have the 14.x installed it should be fine to bump the lib to his last version.

yes, exactly. The issue you faced in https://github.com/awinogrodzki/next-firebase-auth-edge/issues/159 was no longer reproducible in Next.js 14
