### ISSUE TITLE
How to see changelog b/w releases?

### ISSUE THREAD

**Issue by GorvGoyl** [awinogrodzki/next-firebase-auth-edge#175]
It would be great if you could also release updates on GitHub. This way, developers using the library can review the changelog before upgrading.

P.S. Thanks for the awesome library!

**Comment by awinogrodzki** [comment]
Hello @GorvGoyl!

That's good suggestion! I will look into a way to automate github releases with all necessary changelog info!

Thank you

**Comment by awinogrodzki** [comment]
@GorvGoyl I've integrated pipelines with semantic-release, which automatically handles creating and managing github releases. See example release: https://github.com/awinogrodzki/next-firebase-auth-edge/releases/tag/v1.4.4
