### ISSUE TITLE
[Question] How to populate firebase auth with current user?

### ISSUE THREAD

**Issue by trungtin** [awinogrodzki/next-firebase-auth-edge#177]
Hey, thank you for this fantastic library. I have ditched next-auth and migrated to this because the integration is so simple.

But I have a question; looking at the starter example, you suggested that the app should only rely on the server token and use `inMemoryPersistence` to fix the inconsistency issue #143 #163; is there an escape hatch when we want to have the firebase auth populated with the current user (specifically, how to construct the firebase User object)  to use the firebase API like `reauthenticateWithCredential` (I need this API to update re-check the current user password when updating it). I thought I could use the low-level methods from `getFirebaseAuth`, but apparently, those construct a pure object, not the full User object.

Thank you for the help.

**Comment by awinogrodzki** [comment]
Hey @trungtin!

Could you share some code where you update user password? I am interested in methods that you're using.

My guess (not sure it applies 100% to your use case) is that you should re-call `/api/login` endpoint with fresh idToken just after you update user password, but for that I would have to look at some code

**Comment by trungtin** [comment]
```tsx
import {
  EmailAuthProvider,
  reauthenticateWithCredential,
  updatePassword,
  getAuth,
} from "firebase/auth";

import { loginWithCredential } from "../shared/api"; // <-- exactly like the code in starter example

async function updateUserPassword({ currentPassword, newPassword }) {
  try {
    const user = getAuth().currentUser; // <-- this is what I needed for the subsequent calls
    const credential = EmailAuthProvider.credential(
      user?.email!,
      currentPassword
    );
    await reauthenticateWithCredential(user!, credential);
    // ^ reauthenticate to check for current password, also needed for refreshing the token for updatePassword call
    await updatePassword(user!, newPassword);
    const updatedCredential = await reauthenticateWithCredential( // <-- re-authenticate for firebase sdk
      user!,
      EmailAuthProvider.credential(user?.email!, newPassword)
    );
    loginWithCredential(updatedCredential); // <-- finally, re-login with next-firebase-auth-edge
  } catch (error: any) {
    console.error("Error updating password:", error);
  }
}
```
Here's basically what I'm using for updating user passwords. This works, but requires setting the firebase-auth persistence to `browserLocalPersistence`, my question is how to implement this functionality with `inMemoryPersistence`

Thank you.

**Comment by awinogrodzki** [comment]
Thanks for code samples @trungtin !

That's pretty nice use-case that I haven't yet covered.

In order not to use `inMemoryPersistence` with your scenario, instead of using `getAuth().currentUser`, you should fetch user credentials using `signInWithCustomToken`.

To do that, you would have to extend `AuthContext` to also expose user custom token, like so:

```tsx
export interface User extends UserInfo {
  customToken: string; // <--- this
  emailVerified: boolean;
  customClaims: Claims;
}
```

```ts
export const toUser = ({token, decodedToken}: Tokens): User => {
  const {
    uid,
    email,
    picture: photoURL,
    email_verified: emailVerified,
    phone_number: phoneNumber,
    name: displayName,
    source_sign_in_provider: signInProvider
  } = decodedToken;

  const customClaims = filterStandardClaims(decodedToken);

  return {
    uid,
    email: email ?? null,
    displayName: displayName ?? null,
    photoURL: photoURL ?? null,
    phoneNumber: phoneNumber ?? null,
    emailVerified: emailVerified ?? false,
    providerId: signInProvider,
    customClaims,
    customToken: token // <--- Pass `token` from tokens object. It can be referred to as `custom token`
  };
};
```

Then, inside client component, you can use it like so:

```tsx
  const {user} = useAuth();

  async function changePassword(currentPassword: string, newPassword: string) {
    if (!user) {
      return;
    }

    const auth = getFirebaseAuth();
    const {user: firebaseUser} = await signInWithCustomToken(auth, user.customToken);
    const credential = EmailAuthProvider.credential(
      firebaseUser.email!,
      currentPassword
    )
    await updatePassword(firebaseUser, newPassword);
    const updatedCredential = await reauthenticateWithCredential( // <-- re-authenticate for firebase sdk
      firebaseUser,
      EmailAuthProvider.credential(user?.email!, newPassword)
    );
    await loginWithCredential(updatedCredential);
  }
```

I haven't tested this code yet, but it seems to be what you're looking for.

Could you test it and let me know?

**Comment by awinogrodzki** [comment]
I will close the issue now. Feel free to reopen if you face some problems with the approach I proposed
