### ISSUE TITLE
What is the best approach to keeping custom claims synchronised?

### ISSUE THREAD

**Issue by georgecartridge** [awinogrodzki/next-firebase-auth-edge#179]
Hi there

I wanted to seek your advice on a use-case I'm currently dealing with. I wonder if you had any suggestions? 

I'm setting custom claims for the subscription status of users - they can be either `free` or `premium`. The assignment of these claims are done on some serverless functions away from next and vercel. 

My application has protected routes that depend on the user's subscription status. These routes check the user's custom claims passed down by `next-firebase-auth-edge`. If the user has the `premium` subscription claim, then they are allowed to navigate to the route. If the user has the `free` subscription claim, they should be redirected.

What do you think is the best approach to keeping custom claims synchronised in this use-case? Would it be considered bad practice to refresh the response cookie on every route navigation to keep them up-to-date? I'm trying to understand the best approach that wouldn't introduce performance or security issues.

Thank you for your library, @awinogrodzki – it has been a tremendous help in my project. I appreciate any guidance or recommendations you can provide regarding this.

**Comment by awinogrodzki** [comment]
Hey @georgecartridge!

Thanks for the question. It's quite interesting case, which can be boiled down to updating user credentials after some asynchronous, server-side action. 

Refreshing cookie on each route navigation seems a bit extensive.

I've prepared a canary release with new function that would help with your case. You can update `next-firebase-auth-edge` to `1.5.0-canary.3` to get your hands on new `refreshCredentials` method. More on that later.

To make things fast, I would use some distributed cache engine like Redis to check if user credentials should be updated. Let's consider following scenario:

1. User purchases subscription
2. Async action is triggered that updates user custom claims asynchronously
3. After user custom claims are successfully updated, we add new record to distributed cache system, similar to this:
```tsx
cache.set(`purchase_status_update.${user.id}`, true);
```

Now, we can use this information inside our middleware to figure out if we should _refresh user credentials_

First, we need to setup an API route that would check our distributed cache. Like this:

```ts
// /api/subscription-status/route.ts

export async function GET(request: NextRequest) {
  const tokens = await getTokens(request.cookies, authConfig);

  if (!tokens) {
    return NextResponse.json({ shouldUpdateCredentials: false });
  }
  
  const result = await cache.get(`purchase_status_update.${tokens.decodedToken.uid}`);
  
  if (!result) {
    return NextResponse.json({ shouldUpdateCredentials: false });
  }

  return NextResponse.json({ shouldUpdateCredentials: true });
}
```

Now, we can update our `handleValidToken` middleware function to use  the new `refreshCredentials` if user credentials should be updated:

```tsx
// middleware.ts
import {refreshCredentials} from 'next-firebase-auth-edge/lib/next/cookies';

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    // ...
    handleValidToken: async ({token, decodedToken}, headers) => {
      const {shouldUpdateCredentials} = await fetchSubscriptionStatus(); // Call new /api/subscription-status endpoint

      if (shouldUpdateCredentials) {
        return refreshCredentials(request, authConfig, ({headers}) =>
          NextResponse.next({
            request: {
              headers
            }
          })
        );
      }

      return NextResponse.next({
        request: {
          headers
        }
      });
    },
  });
}
```

`refreshCredentials` works very much like `refreshNextResponseCookies`, but additionally allows user to pass [Modified Request Headers](https://vercel.com/templates/next.js/edge-functions-modify-request-header) with updated credentials. Passing Modified Request Headers to `NextResponse.next` is crucial if we want `getTokens` to return the updated credentials **within the same request**

You probably wonder why do we need dedicated API route at all. Why not to call our distributed cache directly from Middleware? We could, but most cache libraries (eg. [node-redis](https://github.com/redis/node-redis)) does not work inside Edge runtime, so we need to create intermediate API route

More information about upcoming `1.5` version and changes can be found in [v1.5.x canary release](https://github.com/awinogrodzki/next-firebase-auth-edge/pull/186) pull request description

Let me know if this helps!

**Comment by awinogrodzki** [comment]
BTW. I've updated official docs with this use case:

https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials

Please note that docs are based on latest canary release

**Comment by georgecartridge** [comment]
Thanks for adding this @awinogrodzki and the time you've taken to go over things. That definitely helps, and I'll be trying this approach soon in my project!
