### ISSUE TITLE
Redirect to Homepage only

### ISSUE THREAD

**Issue by Vicidevs** [awinogrodzki/next-firebase-auth-edge#189]
I changed the authenticated part to "/user" instead of "/" in the middleware but it keeps on directing me to "/"

**Comment by awinogrodzki** [comment]
Hey @Vicidevs,

Could you share your `middleware.ts` file and `next.config.js` file?

**Comment by Vicidevs** [comment]
import { NextRequest, NextResponse } from "next/server";
import {
  authMiddleware,
  redirectToHome,
  redirectToLogin,
} from "next-firebase-auth-edge";
import { authConfig } from "./config/server-config";

const PUBLIC_PATHS = ["/auth/register", "/auth/login", "/auth/reset-password"];

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: authConfig.apiKey,
    cookieName: authConfig.cookieName,
    cookieSerializeOptions: authConfig.cookieSerializeOptions,
    cookieSignatureKeys: authConfig.cookieSignatureKeys,
    serviceAccount: authConfig.serviceAccount,
    handleValidToken: async ({ token, decodedToken }, headers) => {
      // Authenticated user should not be able to access /login, /register and /reset-password routes
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }

      return NextResponse.next({
        request: {
          headers,
        },
      });
    },
    handleInvalidToken: async (reason) => {
      console.info("Missing or malformed credentials", { reason });
      return redirectToLogin(request, {
        path: "/auth/login",
        publicPaths: PUBLIC_PATHS,
      });
    },
    handleError: async (error) => {
      console.error("Unhandled authentication error", { error });
      return redirectToLogin(request, {
        path: "/auth/login",
        publicPaths: PUBLIC_PATHS,
      });
    },
  });
}

export const config = {
  matcher: [
    "/user/:path*",
    "/((?!_next|favicon.ico|_/auth|_/firebase|api|.*\\.).*)",
    "/api/login",
    "/api/logout",
  ],
};

**Comment by Vicidevs** [comment]
next.config.js

/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;

**Comment by awinogrodzki** [comment]
You are using `redirectToHome` helper function from `next-firebase-auth-edge` which redirects to `/` page.

You should write your own redirect function, for example:

```tsx
export function redirectToUser(request: NextRequest) {
  const url = request.nextUrl.clone();
  url.pathname = '/user';

  return NextResponse.redirect(url);
}
```

Then, in middleware use it instead of `redirectToHome`:

```tsx
if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
 return redirectToUser(request);
}
```

**Comment by awinogrodzki** [comment]
I will introduce another function called `redirectToPath` that will help with your cases. I will also update docs to encourage people to write their own redirect functions for more complex use cases.

Thanks for feedback!

**Comment by awinogrodzki** [comment]
Hey @Vicidevs!

Thank you for your patience. 

In [1.7.0-canary.17](https://github.com/awinogrodzki/next-firebase-auth-edge/compare/v1.7.0-canary.16...v1.7.0-canary.17) I've released a new function called `redirectToPath`. You can import it directly from `next-firebase-auth-edge`.

The following example replicates how `redirectToHome` works. 

```ts
    handleValidToken: async ({token, decodedToken, customToken}, headers) => {
      // Authenticated user should not be able to access /login, /register and /reset-password routes
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToPath(request, '/', {shouldClearSearchParams: true});
      }

      return NextResponse.next({
        request: {
          headers
        }
      });
    },
```

Configuration object is optional and accepts a single parameter: `shouldClearSearchParams`, which is `false` by default. I hope the name is descriptive enough.

Let me know how that works! Cheers 🎉
