### ISSUE TITLE
Show Custom Claims of the User

### ISSUE THREAD

**Issue by fesmpydev** [awinogrodzki/next-firebase-auth-edge#190]
I am using Next 14.2.3 and Firebase 10.12.1. On the client's side I am registering users and configuring Custom Claims through the execution of Cloud Functions.

Now, using the Middleware in SRC/Middleware.ts and inside Handlevalidtoken with the code:
 const claims = filterstandardclaims (decodedtoken);
 Console.log (Claims);

I am seeing an empty object. If the token and decodedtoken shows me by console, it shows me their properties.

Maybe I am incorrect, if this is the case I need help please.

**Comment by awinogrodzki** [comment]
Hey @fesmpydev!

You can upgrade to `next-firebase-auth-edge@1.5.2` to use new `refreshCredentials` method inside Middleware, as documented in: https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials#refresh-credentials-in-middleware

In 1.5.2, I introduced an update that exposes `tokens` object in response callback. You can use `tokens.decodedIdToken` to get latest user claims.

Remember that you don't want to call `refreshCredentials` on every request. 

You can follow solution mentioned here: https://github.com/awinogrodzki/next-firebase-auth-edge/issues/179

Let me know if that works!

**Comment by fesmpydev** [comment]
**Perfect** @awinogrodzki , now I can access the Custom Claims without problems 🎉 Thank you very much for that. I have a last question, in the environment variable of:
Auth_cokie_signature_Key_current = secret1
Auth_cokie_signature_Key_previous = secret2

Those are the right values ​​that must go there, or should it change for any value of the Firebase project?

**Comment by awinogrodzki** [comment]
You should change those values to some password-like string
