### ISSUE TITLE
Missing or malformed credentials { reason: 'MISSING_CREDENTIALS' }

### ISSUE THREAD

**Issue by Leon-Achteresch** [awinogrodzki/next-firebase-auth-edge#191]
#### Description
I am encountering an authentication issue when using the `next-firebase-auth-edge` middleware in my Next.js application. The error message I receive is `MISSING_CREDENTIALS`. This issue seems to be related to the Firebase service account credentials not being correctly provided or formatted.

Honestly at this point I dont know how to fix the problem. Hope to get some help :)

#### Current Middleware Configuration
Here is the current setup for my middleware:

```typescript
import { NextRequest, NextResponse } from 'next/server';
import {
  authMiddleware,
  redirectToHome,
  redirectToLogin,
} from 'next-firebase-auth-edge';
import { clientConfig, serverConfig } from './config';

const PUBLIC_PATHS = ['/register', '/login', '/'];

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: '/api/login',
    logoutPath: '/api/logout',
    apiKey: process.env.FIREBASE_API_KEY,
    cookieName: 'AuthToken',
    cookieSignatureKeys: ['secret1', 'secret2'],
    cookieSerializeOptions: {
      path: '/',
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production', // Set to true on HTTPS environments
      sameSite: "lax" as const,
      maxAge: 12 * 60 * 60 * 24, // twelve days
    },
    serviceAccount: {
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    },
    handleValidToken: async ({ token, decodedToken }, headers) => {
      console.info('Authenticated user', { token, decodedToken });
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }

      return NextResponse.next({
        request: {
          headers,
        },
      });
    },
    handleInvalidToken: async (reason) => {
      console.log(request.cookies);
      console.info('Missing or malformed credentials', { reason });

      return redirectToLogin(request, {
        path: '/login',
        publicPaths: PUBLIC_PATHS,
      });
    },
    handleError: async (error) => {
      console.error('Unhandled authentication error', { error });

      return redirectToLogin(request, {
        path: '/login',
        publicPaths: PUBLIC_PATHS,
      });
    },
  });
}

export const config = {
  matcher: ['/((?!_next|api|.*\\.).*)', '/api/login', '/api/logout'],
};

```

#### Steps Taken to Debug

1. **Checked Service Account Configuration:** Ensured the `projectId`, `clientEmail`, and `privateKey` were set correctly.
2. **Formatted Private Key:** Verified the `privateKey` format, ensuring proper line breaks.
3. **Moved Sensitive Information to Environment Variables:** Updated the code to fetch credentials from environment variables.

#### Request for Assistance
I would appreciate any insights or suggestions on resolving this `MISSING_CREDENTIALS` error. Specifically, any guidance on correctly setting up and using the service account credentials with `next-firebase-auth-edge` would be helpful. Thank you!

**Comment by awinogrodzki** [comment]
Hey @Leon-Achteresch!

As pointed out in: https://next-firebase-auth-edge-docs.vercel.app/docs/errors

> The role of InvalidTokenReason is mostly informative. handleInvalidToken is usually called when something expected happens and we can safely redirect user to the login page. One of those expected events might be a user visiting your app for the first time.

`MISSING_CREDENTIALS` is **expected**. It just instructs you that user has opened your app with no credentials attached.

You can just safely ignore this error by removing `console` method execution in `handleInvalidToken`

**Comment by Leon-Achteresch** [comment]
Thanks for the quick response! @awinogrodzki 

I understood the problem. But as soon as I klick my login Button (Login works fine) the URL sets to this: /login?redirect=%2Fhome and nothing happens. 
The middleware should redirect into: handleValidToken.
I think its missing the part to set the cookie?

**Comment by awinogrodzki** [comment]
Could you open Dev Tools, follow to Network tab and record requests before and after you login?

1. Is `/api/login` endpoint being called?
2. Does `/api/login` endpoint respond with status 200 and `Set-Cookie` header with new credentials?
3. After you login, are those cookies being sent along with the request? In Chrome, you can open Dev Tools > Application > Cookies to investigate if cookies are attached to a domain and valid

If all tests pass successfully, could you run your middleware with `debug: true` option and share some logs here?

**Comment by Leon-Achteresch** [comment]
I know about the dev tools haha

The endpoints are not getting called. Here are despite of it the logs:ⓘ next-firebase-auth-edge: Handle request
         path: /home
ⓘ next-firebase-auth-edge: Missing authentication cookies
ⓘ next-firebase-auth-edge: Token is missing or has incorrect formatting. This is expected and usually means that user has not yet logged in
         reason: MISSING_CREDENTIALS
ⓘ next-firebase-auth-edge: Handle request
         path: /login
ⓘ next-firebase-auth-edge: Missing authentication cookies
ⓘ next-firebase-auth-edge: Token is missing or has incorrect formatting. This is expected and usually means that user has not yet logged in
         reason: MISSING_CREDENTIALS

**Comment by awinogrodzki** [comment]
Could you share some logs of the login page? Are you calling `/api/login` endpoint there?

**Comment by Leon-Achteresch** [comment]
```typescript
const handleLogin = async () => {
    const res = await FuncsignInWithEmailAndPassword(email, password);
    if (res) {
      router.push('/home');
    }
  };
.....

<Button className="w-full" color="primary" onClick={handleLogin}>
 Login
</Button>
```

And the SignIn Function ist smt like this:
```typescript
export async function FuncsignInWithEmailAndPassword(
  email: string,
  password: string
): Promise<boolean> {
  
  try {
    const userCredential = await signInWithEmailAndPassword(auth, email, password);

    return true;
  } catch (error) {
 
    console.log(error);
    return false;
  }
}
```

**I just started the project so some stuff could be missing...**
So there is NO call to /api/login :)

**Comment by awinogrodzki** [comment]
You can take a look at Login Page example in library docs: https://next-firebase-auth-edge-docs.vercel.app/docs/getting-started/login-page#example-loginpage

```tsx
    const credential = await signInWithEmailAndPassword(
      getAuth(),
      email,
      password
    );
    const idToken = await credential.user.getIdToken();
 
    // Sets authenticated browser cookies
    await fetch('/api/login', {
      headers: {
        Authorization: `Bearer ${idToken}`
      }
    });
 
    // Refresh page after updating browser cookies
    router.refresh();
```

`/api/login` call is crucial. It sets your browser cookies. After this call, you'll no longer get `missing_credentials` from this particular user 

Cheers 🎉

**Comment by Leon-Achteresch** [comment]
Thanks man! working now :)

**Comment by Henex1** [comment]
Please I am receiving error with message Missing Token after cloning the next-firebase-auth-edge starter example. I have replaced the environment variable with my credentials.

**Comment by awinogrodzki** [comment]
Hey @Henex1! Does the error come from `handleInvalidToken` method?

**Comment by Henex1** [comment]
Yes, ` Error: Invalid argument: idToken has incorrect "iss" (issuer) claim. Expected https://securetoken.google.com/next-tail-auth, but got https://securetoken.google.com/next-firebase-auth-edge-demo`. It seems it is logged in another project while trying to login. But on Emulator mode.

**Comment by awinogrodzki** [comment]
Have you updated project id inside .firebaserc file? https://github.com/awinogrodzki/next-firebase-auth-edge/blob/f5e1241a3d62c3ed40abd4b49632bd8b3e5272ea/examples/next-typescript-starter/.firebaserc

**Comment by Henex1** [comment]
To something like this right?
`{
  "projects": {
    "default": "localhost:3000"
  }
}`

**Comment by awinogrodzki** [comment]
I think in your case it should be:

```json
{
  "projects": {
    "default": "next-tail-auth"
  }
}
```

**Comment by Henex1** [comment]
It's working now, I have to restart the emulator and the local server

**Comment by awinogrodzki** [comment]
In such case, could you verify that `serviceAccount.projectId` that you provide to `authMiddleware` is present and has value `next-tail-auth`?

Could you also clear your browser storage before testing again? You might still have old token with incorrect iss header attached to browser cookies
