### ISSUE TITLE
Update docs for `refreshServerCookies`

### ISSUE THREAD

**Issue by steve-marmalade** [awinogrodzki/next-firebase-auth-edge#198]
Hello, the docs for [Refresh auth cookies in Server Actions](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials#refresh-auth-cookies-in-server-actions) appear to be out-of-date, since `refreshServerCookies` now seems to want three arguments instead of two. 

Am I correct that:

```ts
await refreshServerCookies(cookies(), commonOptions);
```
should be:

```ts
await refreshServerCookies(cookies(), headers(), commonOptions);
```

**Comment by awinogrodzki** [comment]
Hey @steve-marmalade! 

Good catch! Thank you for reporting this, and sorry for inconsistency.

The docs should be up to date now!

**Comment by abusada** [comment]
When I use 
```
await refreshServerCookies(cookies(), headers(), commonOptions);
```

I get:  Headers cannot be modified error, however wrapping `headers()` with `new Headers` fixes it

```
await refreshServerCookies(cookies(), new Headers(headers(), commonOptions);
```

Shouldn't the docs [here](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials#refresh-auth-cookies-in-server-actions) be updated?

**Comment by awinogrodzki** [comment]
Hey @abusada!

Thanks for reporting. You're right, I also noticed this behavior on my side. 

I will update the docs 👍
