### ISSUE TITLE
Invalid argument: idToken has "kid" claim which does not correspond to a known public key.

### ISSUE THREAD

**Issue by VVhispo** [awinogrodzki/next-firebase-auth-edge#203]
Hey, middleware started throwing this error out of nowhere: 

`AuthError: Invalid argument: idToken has "kid" claim which does not correspond to a known public key. Most likely the token is expired, so get a fresh token from your client app and try again.`

It only happens when I use `refreshNextResponseCookies` in order to refetch Firebase data. It's not an issue with a specific account because it happens with freshly created ones.  I've been using the same exact code for few days now and everything worked perfectly until today

**Comment by VVhispo** [comment]
Everything is back to normal now :) No idea what was this about, will reopen if the issue returns

**Comment by awinogrodzki** [comment]
Hey @VVhispo!

handleError can be called with INVALID_ARGUMENT error after Google public keys are updated.

This is a form of key rotation and is expected. [See this Github issue for more info](https://github.com/awinogrodzki/next-firebase-auth-edge/issues/151?ref=hackernoon.com#issuecomment-1952928802)

In future release, I will be moving this error to `handleInvalidToken` method to avoid confusion. Let's keep this issue open to keep it tracked

**Comment by VVhispo** [comment]
Hey, thanks for your answer. 
Could you give me a code example of how to refresh user's cookies after this error happens? For me it only appeared when I used `refreshNextResponseCookies` in API handler and user needed to sign in again for the cookies to refresh. 
I don't know if I misunderstand you here but `handleError` method in `authMiddleware` does not seem to catch the error as well.

**Comment by awinogrodzki** [comment]
> I don't know if I misunderstand you here but handleError method in authMiddleware does not seem to catch the error as well.

Thanks for this insight. You're right. If you got this error from `refreshNextResponseCookies` in API handler, `handleError` won't be able to catch this.

At the moment, only proposed solution is to redirect user to login page and let them sign in again. This is the same behaviour as in official `firebase-admin` library. ie. `firebase-admin` throws `Invalid Argument` error with no fallback or token refresh.

A while ago, I created an experiment PR where I use `refreshToken` to generate new `idToken` after `kid` claims have been declared invalid. I can re-introduce this logic under some experimental flag, if you wish to test it

**Comment by VVhispo** [comment]
Would love to test it if it's something you want to pursue further, however signing out works fine as long as I can handle it for the user.
It's difficult to troubleshoot this error because of how random it is, can you take a look at this code and let me know if this is a good approach?
```
import { getFirebaseAuth as getAuth } from "@/config/firebase";
import { signOut } from "firebase/auth";

catch (err: any) {
    if ("code" in err && err.code === "INVALID_ARGUMENT") {
      await signOut(getAuth());
      return NextResponse.redirect("/api/logout");
    } else return notFound();
  }
```

Should I handle the other error codes from https://next-firebase-auth-edge-docs.vercel.app/docs/errors the same way?

Thanks

**Comment by awinogrodzki** [comment]
I am somehow confused by the code example you provided, as I think `signOut` from `firebase/auth` should be called in client side. Please correct me if that's not the case.

Since the error happens inside API handler, I would handle this case like so:

Inside API handler, where you call `refreshNextResponseCookies` , I would add `try/catch` AuthError and return response with `401 Unauthorized` status: 

```ts
import {AuthError, AuthErrorCode} from 'next-firebase-auth-edge/lib/auth/error';

export function GET(request: NextRequest) {
  try {
    await getTokens(...);

    ...

    return refreshNextResponseCookies(...);
  } catch(e) {
    if (e instanceof AuthError && e.code === AuthErrorCode.INVALID_ARGUMENT) {
       return new NextResponse(JSON.stringify({message: 'Unauthorized'}), {
           status: 401,
           headers: {'content-type': 'application/json'}
       });
    }

   throw e;
  }
}
```

Then, on the client side, when handling the response, I would logout and then redirect user to the login page:

```tsx
import { getFirebaseAuth as getAuth } from "@/config/firebase";
import { signOut } from "firebase/auth";

const response = await fetchApiHandlerResponse('/some-url');

if (!response.ok && response.status === 401) {
  await signOut(getAuth());
  router.redirect('/login');
  return;
}

if (!response.ok) {
  ... handle other issues
}

... handle successful response
```

**Comment by VVhispo** [comment]
Sorry, I should have mentioned it earlier. I do not call the API handler anywhere on my client. It's a part of a longer verification process, user externally gets a link to the API route in which I do some authentication logic and then redirect to a normal route while refreshing the cookies. 

As for the `firebase/auth`  `signOut()` function I'm not sure actually, but I've tested the aforementioned signOut logic in a separate handler and everything seems to work fine. Can you explain why you don't call the `'api/logout'` route in your example? I thought it's a necessary part of the sign out logic.

**Comment by awinogrodzki** [comment]
> Can you explain why you don't call the 'api/logout' route in your example?

Good point. I just missed it. It should be called just after `signOut()`
