### ISSUE TITLE
Issue with refreshing token and react-query/swr

### ISSUE THREAD

**Issue by eanesparrago** [awinogrodzki/next-firebase-auth-edge#209]
Hello! Thank you for this cool library. I found this issue hasn't been discussed yet...

I created authenticated API routes and used react-query on my project and experienced this bug:

1. User loads the web app OK,
2. User leaves the web app open in its tab for a while.
3. User opens the web app tab back open and receives multiple unauthenticated fetch errors.

Thanks to this [issue](https://github.com/awinogrodzki/next-firebase-auth-edge/issues/99#issuecomment-1746907997) I learned that this is caused by:

> Once in 1 hour, when user token becomes invalid, there might be multiple concurrent requests to authenticated routes happening, each call is made with expired token, so each request is causing a token refresh of its own

Since by default, react-query refetches the active API routes on window focus causing multiple concurrent requests.

I've tried 2 fixes:

1. Disabled the preload behavior of Next Link components
2. Disabled `refetchOnWindowFocus` option of react-query

These seem to help but I still encounter the bug occasionally. I might also want to enable the 2 behaviors I disabled. 

A solution I'm thinking about: Somehow reload the page when receiving the unauthenticated error or reload the page on window focus (will check what options Nextjs has for this). But I'm wondering if there is a better option or if I missed something.

Edit: Will explore refreshing the token client side on unauthenticated error..

Here's my middleware...

```
import { NextRequest, NextResponse } from "next/server";
import {
  authMiddleware,
  redirectToHome,
  redirectToLogin,
} from "next-firebase-auth-edge";
import { clientConfig, serverConfig } from "./lib/firebase/firebase-configs";
import { APP_ROUTES } from "@/constants/routes";

const PUBLIC_PATHS: string[] = [APP_ROUTES.LOGIN];

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    cookieSerializeOptions: serverConfig.cookieSerializeOptions,
    serviceAccount: serverConfig.serviceAccount,
    handleValidToken: async ({ token, decodedToken }, headers) => {
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }

      return NextResponse.next({
        request: {
          headers,
        },
      });
    },
    handleInvalidToken: async (reason) => {
      console.info("Missing or malformed credentials", { reason });

      return redirectToLogin(request, {
        path: APP_ROUTES.LOGIN,
        publicPaths: PUBLIC_PATHS,
      });
    },
    handleError: async (error) => {
      console.error("Unhandled authentication error", { error });

      return redirectToLogin(request, {
        path: APP_ROUTES.LOGIN,
        publicPaths: PUBLIC_PATHS,
      });
    },
  });
}

export const config = {
  matcher: ["/", "/((?!_next|api|.*\\.).*)", "/api/login", "/api/logout"],
};
```

Function used in authenticated API routes:

```
export async function validateAuth() {
  try {
    const tokens = await getTokens(cookies(), authConfig);

    if (!tokens) {
      throw new UnauthorizedError();
    }

    return tokens;
  } catch (error) {
    console.log(error);
    throw error;
  }
}
```

**Comment by awinogrodzki** [comment]
Hey @eanesparrago! Thank you for your patience.

In `next-firebase-auth-edge@1.6.1` I've introduced [getValidIdToken](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/client-side-apis#getvalididtoken) function that is designed for this specific case.

Remember to [enable refresh token API route](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/client-side-apis#enable-refresh-token-api-endpoint-in-auth-middleware) in the middleware before using `getValidIdToken`

Let me know if that helps!

**Comment by awinogrodzki** [comment]
I hope the issue is solved. Feel free to re-open if otherwise.

**Comment by eanesparrago** [comment]
> I hope the issue is solved. Feel free to re-open if otherwise.

Thank you! Here's how I got it working on my code...

```
import { useAuth } from "@/components/providers/auth/auth-context";
import { useCallback } from "react";
import { getValidIdToken } from "next-firebase-auth-edge/lib/next/client";
import { API_ROUTES } from "@/constants/api-routes.constants";

const useAppFetch = () => {
  const auth = useAuth();

  const getIdToken = useCallback(async () => {
    return getValidIdToken({
      serverIdToken: auth.serverIdToken ?? "",
      refreshTokenUrl: API_ROUTES.REFRESH_TOKEN,
    });
  }, [auth.serverIdToken]);

  const get = useCallback(
    async (url: string, requestInit?: RequestInit) => {
      try {
        const idToken = await getIdToken();

        const requestOptions = {
          method: "GET",
          headers: {
            Authorization: `Bearer ${idToken}`,
          },
          ...requestInit,
        };

        const response = await fetch(url, requestOptions);

        return handleResponse(response);
      } catch (error) {
        console.error(error);
      }
    },
    [getIdToken],
  );

  const patch = useCallback(
    async (url: string, body: any, requestInit?: RequestInit) => {
      try {
        const idToken = await getIdToken();

        const requestOptions = {
          method: "PATCH",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${idToken}`,
          },
          body: JSON.stringify(body),
          ...requestInit,
        };

        const response = await fetch(url, requestOptions);

        return handleResponse(response);
      } catch (error) {
        console.error(error);
      }
    },
    [getIdToken],
  );

  return {
    get,
    patch,
  };
};

export default useAppFetch;
```
