### ISSUE TITLE
Log in via server actions

### ISSUE THREAD

**Issue by mykz** [awinogrodzki/next-firebase-auth-edge#212]
Hey,

Thank you for creating this amazing package.

I was wondering if it's possible to log in via a server action, as currently, the examples only show the login action performed via a client-side component event handler (handleLogin).

What I'm trying to do is something like this:

```ts
'use server'

import { getAuth, signInWithEmailAndPassword } from 'firebase/auth'
import { app, serverConfig } from '@/firebase'
import { redirect } from 'next/navigation'
import { cookies } from 'next/headers'

export async function loginAction(formData: FormData) {
  const username = String(formData.get('username'))
  const password = String(formData.get('password'))

  try {
    const credential = await signInWithEmailAndPassword(
      getAuth(app),
      username,
      password
    )

    const idToken = await credential.user.getIdToken()

    cookies().set(serverConfig.cookieName, idToken)

  } catch (e) {
    console.log(e)
  } finally {
    redirect('/')
  }
}
```

The problem I have currently is the middleware logs an error:

`Missing or malformed credentials { reason: 'MALFORMED_CREDENTIALS' }`

Then it redirects me to the URL `http://localhost:3000/login?redirect=/`.

I've combed through the documentation and was unable to find a way of doing it. My apologies if I missed something.

//Mike

**Comment by awinogrodzki** [comment]
Hey @mykz,

Thanks for reporting! Great use case.

I released `next-firebase-auth-edge@1.7.0-canary.1` with `refreshCookiesWithIdToken` function that works with Server Actions. It can be used to sign in users. I've added documentation with `loginAction` example: https://next-firebase-auth-edge-docs.vercel.app/docs/getting-started/login-with-server-action

Also, I updated [starter example](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/canary/examples/next-typescript-starter/app/login/LoginPage.tsx#L57) with  *Login with Server Action* feature

<img width="690" alt="Screenshot 2024-07-16 at 23 59 33" src="https://github.com/user-attachments/assets/e7d422c6-3e99-4c64-ba29-268a9994f4a2">

Please note that importing `firebase/auth` library works only inside Node.js and browser environments. In Vercel environment, where Server Actions are run on `Serverless Functions`, `firebase/auth` will throw reference error

That's the reason it's not available in official [starter example page](https://next-firebase-auth-edge-starter.vercel.app/)

Let me know how it works for you!

**Comment by tech-a-go-go** [comment]
@awinogrodzki 

Hi, does it work for the redirect login as well ?

**Comment by awinogrodzki** [comment]
> @awinogrodzki 
> 
> 
> 
> Hi, does it work for the redirect login as well ?

Hey, I haven't tested it with that specific scenario, but I can see some potential issues when it comes to calling 'signInWithRedirect' inside Server Actions. Internally, 'signInWithRedirect' uses 'window.location' to perform a redirect, which most probably will throw an error inside Server Action.

**Comment by tech-a-go-go** [comment]
@awinogrodzki

I got it. Thanks a lot !
