### ISSUE TITLE
AuthProvider not updating after router.push

### ISSUE THREAD

**Issue by StudioCubics** [awinogrodzki/next-firebase-auth-edge#221]
After logging in and accessing the secured page using router.push("/dashboard") the AuthProvider is not updating with the new data. This also happens when logging out!

**Comment by huangfulei** [comment]
did you call router.refresh() after that?

**Comment by awinogrodzki** [comment]
Hey @StudioCubics!

This behaviour is a Next.js limitation. Layout is not-rerendered unless you call `router.refresh()` after doing `router.push()`.

See: https://stackoverflow.com/questions/78123618/how-to-re-render-the-page-while-using-router-push-in-next-js-14-app-directory
