### ISSUE TITLE
keep getting 404 on the server side by POST to /api/dino/get-token

### ISSUE THREAD

**Issue by huangfulei** [awinogrodzki/next-firebase-auth-edge#224]
any idea why this happens?
![Screenshot 2024-07-31 at 20 12 27](https://github.com/user-attachments/assets/7629541d-274c-4768-be9d-faaf26573586)

**Comment by awinogrodzki** [comment]
Hey @huangfulei!

Could you share your `middleware.ts` file? Is `/api/dino/get-token` a path you pass as `loginPath`?

I think you might be missing `/api/dino/get-token` in Middleware config:

```tsx
export const config = {
  matcher: [
    '/',
    '/((?!_next|favicon.ico|__/auth|__/firebase|api|.*\\.).*)',
    '/api/dino/get-token',
    '/api/logout',
    '/api/refresh-token'
  ]
};
```

**Comment by awinogrodzki** [comment]
I will close the issue now. Feel free to re-open if the solution does not work

**Comment by huangfulei** [comment]
It could be my local network issue, I'm not getting 404 now
