### ISSUE TITLE
Using refreshServerCookies in Server Actions

### ISSUE THREAD

**Issue by mitchelladams** [awinogrodzki/next-firebase-auth-edge#225]
Hello,
First, thank you for your hard work on this project. I've enjoyed working with it!

I'm trying to get **refreshServerCookies** to work in my project following the [instructions in the documentation](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials#refresh-auth-cookies-in-server-actions) and have been unsuccessful.

My server action is setup like the example:

`'use server';
export async function refreshUser() {
  const tokens = await getTokens(cookies(), authConfig);
 
  if (!tokens) {
    throw new Error('Unauthenticated');
  }

  console.log('Refreshing user');
 
  await refreshServerCookies(cookies(), headers(), authConfig);
}`

Where exactly should I be calling this to refresh claims information without forcing a login/logout?

When I try calling the above server action from a client component's button click, I get an error that headers can't be modified.

These are my package versions:
firebase: "^10.12.4",
firebase-admin: "^12.2.0",
next: "^14.2.5",
next-firebase-auth-edge: "^1.6.2",
react: "^18.3.1",
react-dom: "^18.3.1",

Any guidance is appreciated.

Mitchell

**Comment by awinogrodzki** [comment]
Hey @mitchelladams! Thanks for reporting.

I've already addressed this in the docs: https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-credentials#refresh-auth-cookies-in-server-actions

```tsx
// headers() needs to be wrapped with new Headers() to work in Server Actions
  await refreshServerCookies(cookies(), new Headers(headers()), commonOptions);
```

Basically, `refreshServerCookies` is designed to work in API handlers, Middleware and Server Actions. It updates `Headers` by default, which is not accepted inside Server Actions, unless we pass a new instance of `Headers`.

In future versions I will remove this limitation and skip updating `Headers` inside Server Actions if possible

Cheers!
