### ISSUE TITLE
Next.js 15 RC support

### ISSUE THREAD

**Issue by mp3por** [awinogrodzki/next-firebase-auth-edge#228]
Hello, does this library support NextJS 15 RC ?

**Comment by awinogrodzki** [comment]
Hey @mp3por!

I have not yet tested the library against Next.js 15 RC

I'll keep you updated on this

**Comment by mp3por** [comment]
I was able to successfully run a simple register/login/logout test on your simplified example by bumping to the following version:

`"next": "15.0.0-rc.0",
    "next-firebase-auth-edge": "^1.6.2",
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522"`

**Comment by awinogrodzki** [comment]
Hey @mp3por,

I released `next-firebase-auth-edge@1.7.0-canary.6` which includes Next.js 15 RC support

Recent [starter example](https://next-firebase-auth-edge-starter.vercel.app/) deployment is also working on Next.js 15 RC and React 19 RC

**Comment by mp3por** [comment]
Thank you :)
