### ISSUE TITLE
`refreshServerCookies` ignores cookie settings

### ISSUE THREAD

**Issue by Onxi95** [awinogrodzki/next-firebase-auth-edge#236]
Hi! Thanks for creating this awesome library - without it, implementing Firebase in our Next.js app dir project would have taken much longer! :muscle: 

# Link to the code that reproduces this issue
https://github.com/awinogrodzki/next-firebase-auth-edge/compare/main...Onxi95:next-firebase-auth-edge:main

# To Reproduce
* use snippet from https://github.com/awinogrodzki/next-firebase-auth-edge/compare/main...Onxi95:next-firebase-auth-edge:main
* go to `examples/next-typescript-minimal`
* create `.env` with the necessary firebase credentials
* start the development server and sign in
* you should see, that `refreshServerCookies` ignore cookie settings, while middleware refresh works as expected

https://github.com/user-attachments/assets/3d09eb44-1548-4bf6-9bba-5816417af905

As you can see in the video, cookie settings are ignored by `refreshServerCookies`

# Version
```
"next-firebase-auth-edge": "^1.7.0-canary.2",
```

# :mag_right: Hypothesis

It looks like the parameters for setting cookies are missing [in this part.](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/src/next/cookies.ts#L152-L158)

```TS
export function appendCookie(
  cookies: RequestCookies | ReadonlyRequestCookies,
  signedTokens: string,
  options: SetAuthCookiesOptions
) {
  //                                                 v missing part?
  cookies.set(options.cookieName, signedTokens, options.cookieSerializeOptions);
}
```

I'm not sure if it's the only place, though. :thinking: If there's anything I can help you with, let me know!

**Comment by awinogrodzki** [comment]
Hey @Onxi95! 

Thanks for a heads up! I am glad you find the library helpful 🙌 

Thanks so much for the reproduction and great problem description. It helped me to immediately focus on the fix.

You are right, I've missed to pass serialization options to cookie setter. 

I've prepared a fix and will push to canary branch shortly

**Comment by awinogrodzki** [comment]
> I'm not sure if it's the only place, though. 

I also fixed two other issues on the occasion. Thanks for that 🎉 

The fix has been released in `v.1.7.0-canary.9`. Could you try it and let me know how it works?

**Comment by Onxi95** [comment]
Hello @awinogrodzki!

Works like a charm :muscle: Thanks for a really quick response and fix! I think we can close the issue :smile: have a nice day!
