### ISSUE TITLE
Invalid argument: idToken has incorrect "iss" (issuer) claim. Expected https://securetoken.google.com/undefined

### ISSUE THREAD

**Issue by harshmathurx** [awinogrodzki/next-firebase-auth-edge#240]
Facing this error 
Invalid argument: idToken has incorrect "iss" (issuer) claim. Expected https://securetoken.google.com/undefined, but got https://securetoken.google.com/<my project id>

**Comment by huangfulei** [comment]
most likely your project id is undefined

**Comment by awinogrodzki** [comment]
Hey @harshmathurx,

As @huangfulei suggested, please check if you pass correct `serviceAccount.projectId` value to `authMiddleware` and `getTokens`

**Comment by harshmathurx** [comment]
Let me check that
