### ISSUE TITLE
Using with Flutter apps

### ISSUE THREAD

**Issue by ggukggukee** [awinogrodzki/next-firebase-auth-edge#247]
I want to use this library for my nextjs app that also serves for flutter mobile apps (android and ios) that use api routes to authenticate, fetch data from database and etc.
Will this library work for that purposes and if yes what i have to change in my code to work with flutter apps?

**Comment by awinogrodzki** [comment]
Hey @ggukggukee!

Yes, the library should work just fine, but will require a slightly different approach than seen in examples.

When communicating with Next.js backend from Flutter app, backend won't be able to save or read authentication cookies. 

In Flutter app, you can use native Firebase library to get hold on **ID token**: https://stackoverflow.com/questions/45563320/how-to-get-the-id-token-from-firebaseauth

When making requests to Next.js backend, you should include the ID token in request headers. You can use [Bearer token](https://reqbin.com/req/adf8b77i/authorization-bearer-header) approach

Then, in Next.js API routes, you should extract the token from the request and call [verifyIdToken](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/advanced-usage#getfirebaseauth) from `next-firebase-auth-edge`. Please note that `verifyIdToken` will throw [AuthError](https://next-firebase-auth-edge-docs.vercel.app/docs/errors#handleerror) if token is invalid or expired, so you need to handle the error by yourself. Eg. you can respond with `403 Forbidden` HTTP error. 

See this example:

```tsx
import { getFirebaseAuth } from 'next-firebase-auth-edge/lib/auth';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { authConfig } from '../../../config/server-config';

const {verifyIdToken} = getFirebaseAuth({
  serviceAccount: authConfig.serviceAccount,
  apiKey: authConfig.apiKey
});

export async function POST(request: NextRequest) {
  const token = request.headers.get('Authorization')?.split(' ')[1];

  if (!token) {
    return NextResponse.json({error: 'Unauthorized'}, {status: 401});
  }

  try {
    const decodedToken = await verifyIdToken(token);

    await performSecureActionForUser(decodedToken.uid);
  } catch (e) {
    console.error(e);
    return NextResponse.json({error: 'Forbidden'}, {status: 403});
  }
}
```

**Comment by ggukggukee** [comment]
Thank you for your answer
