### ISSUE TITLE
Use this library to process register

### ISSUE THREAD

**Issue by jayli3010** [awinogrodzki/next-firebase-auth-edge#248]
I already know that login and logout are processed by default, but if I want to use this to process register, should I add a new processing logic from handleInvalidToken ()?

**Comment by awinogrodzki** [comment]
Hey @jayli3010,

I am not sure I understand what you mean by `process register`.

`next-firebase-auth-edge` does expose [createUser](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/advanced-usage#getfirebaseauth) advanced method that you can use to create user account from Middleware or API route, but for most use-cases, it's enough to rely on [official Firebase Auth library](https://firebase.google.com/docs/auth/web/password-auth) to register user accounts. 

Here's how registration is handled in **minimal** example: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next-typescript-minimal/app/register/page.tsx#L27

If you want to login user directly after registration, you can call `/api/login` endpoint with ID token extracted from user credential:

```tsx
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";

//...
      const credential = await createUserWithEmailAndPassword(getAuth(), email, password);

      await fetch("/api/login", {
        headers: {
          Authorization: `Bearer ${await credential.user.getIdToken()}`,
        },
      });

      router.push("/profile");
```

This is similar as in [starter example](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next-typescript-starter/app/register/RegisterPage.tsx#L31-L37)

**Comment by jayli3010** [comment]
Thank you for your explanation. I realized that I had misunderstood the registration process in authentication. There's no need to check API permissions when signing up.
