### ISSUE TITLE
 Cannot read properties of undefined (reading 'privateKey') - getFirebaseAuth()

### ISSUE THREAD

**Issue by Faraz643** [awinogrodzki/next-firebase-auth-edge#255]
Hey, 
I am using official firebase library for user sign in. When the user signs in, I store the user token in cookie as 'fireBaseToken'.
Now in the middleware I am using next-firebase-auth-edge lib. for verifying the token when user tries to access restricted pages. 
After surfing through documentation, I found that verifyIdToken is used in to verify tokens from firebase. 
So I wrote this code (in the attached screenshot), but getting error.

What am I doing wrong? Is there any other method I have to use? Is there any other alternative? Please look for the issue ASAP !
![Frame 2](https://github.com/user-attachments/assets/69d2ba47-a8ac-4da6-8226-5f060faf3b9f)
![middleware 2](https://github.com/user-attachments/assets/73cccd27-ce44-4793-8a6e-54492cbf6fd6)

[i will use env var later]

**Comment by Faraz643** [comment]
even when writing any random string it throws same error. For example in -> 
```
{
..., privateKey: 'Hi all'
}
```

**Comment by awinogrodzki** [comment]
Hey @Faraz643, thanks for reporting

Is this the only place where you call `getFirebaseAuth`?

Do you have access to the full stack trace of this error?

`getFirebaseAuth` would only throw this error if you did not provide first argument to `getFirebaseAuth` function. I may be missing some context here however, so let's first investigate the stack trace

**Comment by Faraz643** [comment]
> Hey @Faraz643, thanks for reporting
> 
> Is this the only place where you call `getFirebaseAuth`?
> 
> Do you have access to the full stack trace of this error?
> 
> `getFirebaseAuth` would only throw this error if you did not provide first argument to `getFirebaseAuth` function. I may be missing some context here however, so let's first investigate the stack trace

This is the only file (middleware) where I am calling getFirebaseAuth

**Comment by Faraz643** [comment]
ISSUE SOLVED
