### ISSUE TITLE
Help regarding minimal set up

### ISSUE THREAD

**Issue by FrugalX** [awinogrodzki/next-firebase-auth-edge#267]
I am trying to run the minimal example locally. However, I am encountering an error after going through the basic setup steps. Could you help me understand why this is happening.

![error](https://github.com/user-attachments/assets/08b80162-83fc-4b7b-b797-5c331160b400).

**Comment by mitchelladams** [comment]
Make sure you have a .env.local file in the project containing all the different configurations. 

e.g.
```
AUTH_COOKIE_SIGNATURE_KEY_CURRENT="KEY-01"
AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS="KEY-01"
```

**Comment by FrugalX** [comment]
i do have .env.local file. But i am not sure what all configurations will be needed. I went through the config.js file and saw the configuration they are using there.  I am not sure where to get my AUTH_COOKIE_NAME, AUTH_COOKIE_SIGNATURE_KEY_CURRENT and AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS

**Comment by mitchelladams** [comment]
See here: https://next-firebase-auth-edge-docs.vercel.app/docs/getting-started/middleware

The AUTH_COOKIE_NAME is just a string for what you want the cookie name to be.

The signature keys are at least 32 bit random strings.  I use the Auth.js CLI to generate a random one in the terminal.

`npx auth secret --raw`
