### ISSUE TITLE
Refreshing `customClaims`

### ISSUE THREAD

**Issue by steve-marmalade** [awinogrodzki/next-firebase-auth-edge#27]
If `customClaims` are updated for a user after they have logged-in via the middleware, when is it expected for the `tokens` to reflect this change? Is there a way to force a refresh, similar to `firebase.auth().currentUser.getIdToken(true)`? Or is the idea that the client-side authentication should detect this and call `/api/login` with the new token?

**Comment by awinogrodzki** [comment]
@steve-marmalade, if there's a change in the token structure, you should call `/api/login` to reflect those changes in cookies. That's how I do it at the moment. 

Technically, I could allow `authentication` middleware function to update the cookies when called with `checkRevoked`.
So, you could conditionally enable `checkRevoked` flag in middleware, which would make a call to firebase and update the cookies with new custom claims. 

For that, I'd have to know when does the change in `customClaims` happen? Is it on client-side, or on backend-side (eg. some worker checks against database and updates the claims)?

**Comment by steve-marmalade** [comment]
Hi @awinogrodzki - this change is happening on the backend-side, but it's in response to request from the client that goes through middleware. I currently am only calling `/api/login` from the client, but would it be possible to call `/api/login` from within the middleware and propagate those cookies in the response to the client? If not, having a flag I can set like `checkRevoked` would be convenient.

**Comment by awinogrodzki** [comment]
@steve-marmalade, 

Got it. `checkRevoked` is not especially useful in this case as it makes a call to user profile endpoint and does not return any updated credentials. What would be useful is method such as `refreshTokenCookies(response: NextResponse, token: string, options: AuthenticationOptions): Promise<NextResponse>`.

Is the backend endpoint that sets custom claims a middleware or api handler? I presume it's an api handler, since setCustomUserClaims method is not yet supported in next-firebase-auth-edge (working on this as well)

**Comment by steve-marmalade** [comment]
Yes, exactly, through an API handler. The refresh function and/or the ability to set the claims directly in middleware make sense to me!

**Comment by awinogrodzki** [comment]
@steve-marmalade,

In `v0.4.4` I introduced `refreshAuthCookies` method to work with Next.js API middleware. You can see /api/refresh-tokens example endpoint in action in [live demo](https://next-firebase-auth-edge-static-demo.vercel.app/)

Usage in API routes:
https://github.com/awinogrodzki/next-firebase-auth-edge/pull/28/files#diff-c513cc42d52f4a53e5be3cba3788502197003ec08618d823daff4174e83e2969R11

Usage in client:
https://github.com/awinogrodzki/next-firebase-auth-edge/pull/28/files#diff-324f3fa45191bc7ee3a6d31b8f61be193531e9b1663e2cf3a08164ce6e091093R27

**Comment by awinogrodzki** [comment]
Using `refreshAuthCookies` automatically sets `Set-Cookie` headers with refreshed cookies in response. Additionally, it returns a set of updated idToken and refreshToken, in case you want to do something with it
