### ISSUE TITLE
Starter Code: App router to pages rotuer

### ISSUE THREAD

**Issue by FrugalX** [awinogrodzki/next-firebase-auth-edge#270]
Hi, we have developed our app in nextjs pages router. We want to implement the starter codebase in our application. Since the starter codebase is developed in app router migrating it to pages router is proving to be difficult. 

If you already have a codebase in pages router would it be possible for you to share it?

**Comment by awinogrodzki** [comment]
Hey @FrugalX,

There is no specific example that relies on pages router, but most of the configuration happens in Middleware.ts, which would be the same for Pages Router and App Router.

You can follow [Getting Started Guide](https://next-firebase-auth-edge-docs.vercel.app/docs/getting-started) from the docs until you reach [Layout](https://next-firebase-auth-edge-docs.vercel.app/docs/getting-started/layout) section, which is dedicated for App Router.

Then, you can follow [Usage in getServerSideProps](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/get-server-side-props) guide to get user token from NextApiRequest using `getApiRequestTokens` function.

There's also a guide on using `getApiRequestTokens` function in conjunction with [Pages Router API Routes](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/pages-router-api-routes)

Let me know when you have any problems when setting up the library
