### ISSUE TITLE
/api/login not found 

### ISSUE THREAD

**Issue by mufarrah** [awinogrodzki/next-firebase-auth-edge#274]
I tried multiple times to call the /api/login route but its not showing 404  :

login-form.tsx:90 
 GET http://localhost:3000/api/login 404 (Not Found)

here is my middleware.ts file
 
`
import { NextRequest, NextResponse } from "next/server";
import {
  authMiddleware,
  redirectToHome,
  redirectToLogin,
} from "next-firebase-auth-edge";
import { clientConfig, serverConfig } from "./config";
const PUBLIC_PATHS = ["/register", "/login"];
export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    cookieSerializeOptions: serverConfig.cookieSerializeOptions,
    serviceAccount: serverConfig.serviceAccount,
    handleValidToken: async ({ token, decodedToken, customToken }, headers) => {
      // Authenticated user should not be able to access /login, /register and /reset-password routes
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }
      return NextResponse.next({
        request: {
          headers,
        },
      });
    },
    handleInvalidToken: async (reason) => {
      console.info("Missing or malformed credentials", { reason });

      return redirectToLogin(request, {
        path: "/login",
        publicPaths: PUBLIC_PATHS,
      });
    },
    handleError: async (error) => {
      console.error("Unhandled authentication error", { error });

      return redirectToLogin(request, {
        path: "/login",
        publicPaths: PUBLIC_PATHS,
      });
    },
  });
}

export const config = {
  matcher: ["/", "/((?!_next|api|.*\\.).*)", "/api/login", "/api/logout"],
};

`

**Comment by awinogrodzki** [comment]
Hey @mufarrah,

What if you change your `config.matcher` to this?

```tsx
export const config = {
  matcher: [
    "/",
    "/((?!_next|api|.*\\.).*)",
    "/api/login",
    "/api/logout",
  ],
};
```

Is the endpoint still returning 404?

If yes, could you share the output of `npx next info` command?

**Comment by mufarrah** [comment]
@awinogrodzki 
i don't see any change to the matcher you gave me !! 
here is the output of the npx next info : 

` npx next info

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32510
  Available CPU cores: 24
Binaries:
  Node: 18.20.4
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // An outdated version detected (latest is 15.0.3), upgrade is highly recommended!
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
 ⚠ An outdated version detected (latest is 15.0.3), upgrade is highly recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue`

**Comment by awinogrodzki** [comment]
Hey @mufarrah,

Thanks for getting back on this. The configuration looks good – I don't see why you would receive 404 when calling `/api/login` endpoint.

First of all, I need to verify if Middleware is actually executed for `/api/login` and other pages.

Could you [enable debug mode](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/debug-mode), by setting `debug: true` in middleware options, and share some logs?

**Comment by awinogrodzki** [comment]
No worries, I am glad you've worked it out! Cheers 🎉

**Comment by carlosromanxyz** [comment]
Hi @awinogrodzki please update this tutorial or add a note: https://hackernoon.com/using-firebase-authentication-with-the-latest-nextjs-features

Because, when I use `/src`, the files will be created it inside this folder ("root project" is outside this folder), this solve 404 error ( and some headaches :D )

Great work!

Thanks
