### ISSUE TITLE
[Help]: Guide to setup firebase server authentication independent of nextjs

### ISSUE THREAD

**Issue by discoverlance-com** [awinogrodzki/next-firebase-auth-edge#279]
Hello,

Thanks for the package, it's very good and works well with nextjs, I am exploring how it could work without next.js given that one is using a framework that supports the features we used here like middleware in nextjs and api routes. For instance, one could use hono and integrate firebase authentication on the server with another framework other than Next.JS.

I know that this framework uses Next.JS concepts like middlewares a lot. So in a case where I am still able to implement this process, I am wondering how I can go about it. 

I know the question I am asking about is a whole different package or codebase altogether that could result from it but I want to know if you have a general guide you could provide for situations where I also want to implement something similar, at least the basics of adding server based authentication like this package does. 

I guess the best option might be to just deep dive into the codebase but just in case you have any guide on the package, that will be useful.

**Comment by awinogrodzki** [comment]
Hey @discoverlance-com,

I use `next-firebase-auth-edge` in two Next.js apps that are part of [ensite](https://ensite.in). The project has distributed service architecture. It has number of external API services written in Node.js.

The process is quite simple:

1. Next.js app allows user to login and saves user token in cookies, using `next-firebase-auth-edge`
2. When making request to external Node.js API service, I include **ID Token** in request headers. 
3. In Node.js service, I use [Firebase Admin SDK's verifyIdToken](https://firebase.google.com/docs/auth/admin/verify-id-tokens) method to validate and parse the ID token

There is no need to use `next-firebase-auth-edge` if your app does not use Next.js. Most functionalities are already present in official Firebase libraries.

>  but I want to know if you have a general guide you could provide for situations where I also want to implement something similar, at least the basics of adding server based authentication like this package does.

`next-firebase-auth-edge` replicates most methods from `firebase-admin` library, but makes it compatible with Edge environment. Assuming you're going to use Node.js, you can use `firebase-admin` library directly. It allows to generate custom token, verify id tokens etc. 

Firebase Admin SDK does not generate, encrypt or validate user cookies, so you'd have to implement this on your own. 

`next-firebase-auth-edge` relies on refresh token to keep alive the user session. Refresh token is acquired using `https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken` endpoint. I am not sure if `firebase-admin` library abstracts this call, so you might need to fetch it explicitly
