### ISSUE TITLE
`ReadonlyRequestCookies` changed the definition location in the latest NextJs 13.3

### ISSUE THREAD

**Issue by MartinXPN** [awinogrodzki/next-firebase-auth-edge#37]
Thanks a lot for the amazing library! I've been using it for the last month or so and it works like a charm.
I was trying to migrate to NextJS 13.3 today (which was released yesterday) and seems like there is a small issue with the `ReadonlyRequestCookies`.
In the previous version of NextJS they defined it in `next/dist/server/app-render` but in the current one seems like the definition has changed to a different location and should be imported from `next/dist/server/web/spec-extension/adapters/request-cookies`. Although I'm not sure if that's the only place to import the cookie type (maybe there is a better way of importing the type).

**Comment by awinogrodzki** [comment]
@MartinXPN thanks a lot for reporting the issue. I will update the imports in next release

**Comment by awinogrodzki** [comment]
@MartinXPN the issue is now fixed in `next-firebase-auth-edge@0.6.1`.

Let me know how it works :-) Cheers 🎉
