### ISSUE TITLE
Problems with Turbopack?

### ISSUE THREAD

**Issue by andreemic** [awinogrodzki/next-firebase-auth-edge#38]
The middleware works stellar with `next dev` but something weird is going on with `next dev --turbo`.

After login the token cookie is set, the redirect occurs (to a "/" page for my app) but that very request denies because the same token is said to be invalid. 

Any ideas?

**Comment by awinogrodzki** [comment]
Hey @andreemic,

Thanks for reporting. I tested `next dev --turbo` with `next13-typescript-static-pages` example and it seems to be working after a minor change in `.env` file:

https://github.com/awinogrodzki/next-firebase-auth-edge/commit/ceccba368dd24e41863acc4f903d6d95e6127e38

It seems that turbopack's env loader cannot parse strings with new line characters without quotation marks.

Other than that it seems to be working fine. Could you check your `.env` file? If the issue persist, could you share some more info about your setup? It could be:

* Next.js version
* Node.js version
* `next-firebase-auth-edge` version
* Error characteristics – Ideally a failing request/response details from dev tools Network tab

**Comment by andreemic** [comment]
> Hey @andreemic,
> 
> Thanks for reporting. I tested `next dev --turbo` with `next13-typescript-static-pages` example and it seems to be working after a minor change in `.env` file:
> 
> [ceccba3](https://github.com/awinogrodzki/next-firebase-auth-edge/commit/ceccba368dd24e41863acc4f903d6d95e6127e38)
> 
> It seems that turbopack's env loader cannot parse strings with new line characters without quotation marks.
> 
> Other than that it seems to be working fine. Could you check your `.env` file? If the issue persist, could you share some more info about your setup? It could be:
> 
> * Next.js version
> * Node.js version
> * `next-firebase-auth-edge` version
> * Error characteristics – Ideally a failing request/response details from dev tools Network tab

Hey, thanks for your answer! I'll collect the info in the following week.

**Comment by awinogrodzki** [comment]
I will close the issue. If there's any other queries feel free to open another one. I'll be glad to help!
