### ISSUE TITLE
Difference between calling `/api/login` and `refreshAuthCookies`?

### ISSUE THREAD

**Issue by KeisukeNagakawa** [awinogrodzki/next-firebase-auth-edge#39]
Hi, frist of all, thank you for this great library.

Is there any difference on  calling `/api/login` and `refreshAuthCookies` when intented to refresh auth cookies? Thanks

**Comment by awinogrodzki** [comment]
Hey @KeisukeNagakawa,

Good question. `/api/login` works basically the same as `refreshAuthCookies`, but there's a small difference to the latter.

Before `refreshAuthCookies`, if you had some `API route` that changed custom user claims, you would have to call `/api/login` immediately after from the client side to update the cookies. Eg. client would have to do:
1. `POST /api/endpoint-that-changes-token-structure`
2. `GET /api/login`

This has couple of drawbacks – something can happen between first and second call (eg. network interruption, an error, etc.) which will cause a discrepancy between client token and the actual state in Firebase. 

`refreshAuthCookies` allows us to return `Set-Cookie` headers along with `/api/endpoint-that-changes-token-structure` response, eliminating the need for a second call to `/api/login`. Client no longer has to know or care to update the tokens, and we also save 1 network roundtrip :-)

I hope this answers your question.

Cheers 🎉

**Comment by KeisukeNagakawa** [comment]
@awinogrodzki  Thank you! I see. Great explanation.
