### ISSUE TITLE
Cookies are empty when site comes from redirect

### ISSUE THREAD

**Issue by nelsonweze** [awinogrodzki/next-firebase-auth-edge#42]
Hi, thanks for this package. It's really been helpful.

I noticed this issue, originally posted [here](https://github.com/vercel/next.js/discussions/17612). 
I have tried setting the `sameSite` to 'lax' but id didn't seem to solve the issue.  In my case, it's redirecting from a payment page on a third party site.

Do you have any ideas or solution?

**Comment by awinogrodzki** [comment]
@nelsonweze thanks for reporting! It so happens that I was already looking into this issue. Will keep you posted here :-)

**Comment by awinogrodzki** [comment]
@nelsonweze, I have reproduced the scenario in following configurations:

1. Redirect from http domain A to http domain B and back
2. Redirect from http domain A to https domain B and back
3. Redirect from https domain A to https domain B and back

All seem to work fine when `sameSite` is set to `lax`. 

You can test it here: https://next-firebase-auth-edge-static-demo.vercel.app/ 
Login via google account, click "go to profile page" following by "redirect" at the bottom.

Note that happens between different https domains.

Here's the `middleware.ts` implementation for example above: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-static-pages/middleware.ts#L29

Could you confirm that the cookies are set with `samesite=lax` in browser dev tools?

<img width="1336" alt="Screenshot 2023-04-29 at 01 41 59" src="https://user-images.githubusercontent.com/12574743/235300329-64fc7d37-cf8d-4c96-8c57-dc4de3556beb.png">
