### ISSUE TITLE
Can i use it without appDir?

### ISSUE THREAD

**Issue by haramishra** [awinogrodzki/next-firebase-auth-edge#44]

**Comment by awinogrodzki** [comment]
Hey @haramishra, great question.

Yes you can. Just setup `middleware.ts` according to the readme and then use `getTokensFromObject` from either API Routes or `getServerSideProps`. I've added some basic examples here: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/README.md#api-routes-or-getserversideprops 

Let me know if you're missing something, cheers!

**Comment by haramishra** [comment]
@awinogrodzki  Thanks for the help.
