### ISSUE TITLE
Question: Why `await import("firebase/auth")?

### ISSUE THREAD

**Issue by KeisukeNagakawa** [awinogrodzki/next-firebase-auth-edge#45]
Hi, first of all, thank you for this great library. I'm loving it.

I have a question! Why do you prefer 
```
  const { getAuth } = await import("firebase/auth");
```

than just importing "firebase/auth" at the top of it?

Thanks!

**Comment by awinogrodzki** [comment]
Hey @KeisukeNagakawa!

Although new versions of firebase for web is modular, `firebase/auth` still adds about 40kb to the bundle. It's a bit of a hack to help reduce initial bundle and defer loading of firebase/auth scripts until page renders for the first time. It might be a bit overkill, but it helped me to improve PageSpeed stats by doing this.

Here are the stats for version with async import:
<img width="740" alt="Screenshot 2023-04-29 at 13 58 26" src="https://user-images.githubusercontent.com/12574743/235301619-e998161d-4323-43a9-abc2-0071aa1d3343.png">

And with static import:
<img width="638" alt="Screenshot 2023-04-29 at 14 02 25" src="https://user-images.githubusercontent.com/12574743/235301641-c3c4a5a2-a77a-42fd-ad32-74db358ba4b6.png">

**Comment by KeisukeNagakawa** [comment]
I see. Thank you for your detailed explanation!
