### ISSUE TITLE
Server Side Rendered Firestore example

### ISSUE THREAD

**Issue by SudhanshuBhagwat** [awinogrodzki/next-firebase-auth-edge#46]
Hi,

Could you please have an example of the same with some server side rendered pages using firestore to get data, like maybe using Firebase Admin SDK or something. That would be really helpful

Thanks

**Comment by awinogrodzki** [comment]
Hey @SudhanshuBhagwat,

I've added a simple firestore database save/update in `next13-typescript-static-pages` example.

[This commit](https://github.com/awinogrodzki/next-firebase-auth-edge/commit/43e32bef8ee0eb77e31abc4cc022352219b8924f) introduces a new API Route that creates and updates a simple counter in database based on user id.

You can also test it on [demo profile page](https://next-firebase-auth-edge-static-demo.vercel.app/profile) by clicking `Update user counter in database`. Just open Network tab in Dev console to inspect the response :-)
