### ISSUE TITLE
add npm link to readme

### ISSUE THREAD

**Issue by KeisukeNagakawa** [awinogrodzki/next-firebase-auth-edge#48]
Hi, 

I think you should add npm package link to readme. Sometimes  it was difficult for me to find npm package for this github. :D

https://www.npmjs.com/package/next-firebase-auth-edge

**Comment by awinogrodzki** [comment]
Hey @KeisukeNagakawa , 

Thanks for the suggestion :-) I've added npm badge and link to readme 

Cheers 🎉

**Comment by KeisukeNagakawa** [comment]
Thanks! I love this package.
