### ISSUE TITLE
Auth lost when project is saved (and fast refresh performs full reload) or when refreshing browser

### ISSUE THREAD

**Issue by clarencefoy** [awinogrodzki/next-firebase-auth-edge#49]
First of all, I am loving this library. I'm quite new to TypeScript (but know React well) and NextJS...and Firebase. So I'm learning a lot of new things here, so please bear with me.

I started with the example app and made a few modifications. Let me provide code examples and step through what the issue is:

First, I added email signup, so on `LoginPage.tsx` there's now two additional inputs and an extra button:

```
      <input
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
      ></input>
      <input
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Password"
      ></input>
      {!hasLogged && (
        <Button
          loading={isLoading}
          disabled={isLoading || !tenant}
          onClick={handleLoginWithEmailAndPassword}
        >
          Log in with Email and Password
        </Button>
      )}
```

Which calls

```
  const handleLoginWithEmailAndPassword = async () => {
    setHasLogged(false);
    const auth = await getFirebaseAuth();
    const tenant = await loginWithEmailAndPassword(auth, email, password);
    await fetch("/api/login", {
      method: "GET",
      headers: {
        Authorization: `Bearer ${tenant.idToken}`,
      },
    });
    setHasLogged(true);
    const redirect = params?.get("redirect");
    router.push(redirect ?? "/");
  };
```

**My first question:**
1.) I can see that the endpoint `/api/login` is being fetched, but under the `pages/api/` folder I can't find a file named `login`. So where does this api endpoint come from?

The function `loginWithEmailAndPassword` is situated within `firebase.ts` and looks like this:

```
export const loginWithEmailAndPassword = async (
  auth: Auth,
  email: string,
  password: string
): Promise<Tenant> => {
  const result = await signInWithEmailAndPassword(auth, email, password)
  const tokenResult = await result.user.getIdTokenResult();
  return {
    id: result.user.uid,
    name: result.user.displayName || null,
    email: result.user.email || null,
    isAnonymous: false,
    emailVerified: true,
    photoUrl: result.user.photoURL,
    customClaims: filterStandardClaims(tokenResult.claims),
    idToken: tokenResult.token,
  };
};
```

**My second question:**
2.) In `middleware.ts`, a token validation function looks for email_verified to assess whether a token is valid:
```
    //isTokenValid: (token) => token.email_verified ?? false,
    isTokenValid: (token) => true,
```
Is that the main mechanism for determining whether a token is valid, or is this just additional validation needed in an app that specifically requires email validation? And would it be possible to redirect to a specific page, or show a message saying 'please verify your email before continuing', if your app needed email verification?

I've set `emailVerified: true`, and forced `isTokenValid` to true but let's assume I am building a service that doesn't require email verification (and for future purposes wouldn't allow anonymous logon either)

This then redirects to `/profile`. Within the `UserProfile.tsx` file I have added the following `UseEffect`:

(with these new imports:

```
import { getApp } from "firebase/app";
import {
  getFirestore,
  collection,
  query,
  where,
  getDocs,
} from "firebase/firestore";
```
)

```
  React.useEffect(() => {
    if (tenant?.id) {
      setBusinessesLoading(true);
      const q = query(
        collection(getFirestore(getApp()), "businesses"),
        where("user_id", "==", tenant.id)
      );
      const getBusinesses = async () => {
        const querySnapshot = await getDocs(q);

        let businessArr = [];
        querySnapshot.forEach((doc) => {
          console.log("getBusinesses -> ", doc.id, " => ", doc.data());
          businessArr.push(doc.data());
        });

        setBusinesses(businesses);
        setBusinessesLoading(false);
      };
      getBusinesses();
    } else {
      console.log("There was no tenant id");
    }
  }, []);
```

**My third question:**
3.) Presumably I don't actually need to check for `if(tenant.id)`, since authentication should already have been handled by the middleware here?

**And finally, the actual issue:**

When initially logging in and visiting this page, the businesses are successfully retrieved. When saving a change, or refreshing the page, it would appear that firestore doesn't "remember" its authentication and throws the error ```Uncaught FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).``` which I know to be the error indicating that login information was lost.

I had hoped that doing my fetch in a 'use client' component would automatically mean my user is authenticated, but perhaps I misunderstood how this is supposed to work?

(please note that my firestore rules permit the reading of any documents so long as the user is authenticated, and since it works on the initial login, we can rule this out as an issue)

I am grateful for any pointers in the right direction.

**Comment by awinogrodzki** [comment]
Hey @clarencefoy! I am happy you find the library useful. Thanks for providing great context to your questions. It looks like you'd like to understand what's happening under the hood and that's a trait of every great developer :-)

> 1.) I can see that the endpoint /api/login is being fetched, but under the pages/api/ folder I can't find a file named login. So where does this api endpoint come from?

It's being handled by `authorization` function in `middleware.ts`.  [Next.js middleware](https://nextjs.org/docs/pages/building-your-application/routing/middleware) is being called on each request and before Next.js page is rendered. It's a perfect place for authentication logic, as it allows you to read and write response headers, redirect to other page if user is not authorized to view given url, etc. 

It's as simple as this: 
https://github.com/awinogrodzki/next-firebase-auth-edge/blob/b92ffd46f64d0e516221e7b3b1c12459eacd6452/src/next/middleware.ts#L34

> 2.) In middleware.ts, a token validation function looks for email_verified to assess whether a token is valid:

    //isTokenValid: (token) => token.email_verified ?? false,
    isTokenValid: (token) => true,

> Is that the main mechanism for determining whether a token is valid, or is this just additional validation needed in an app that specifically requires email validation? And would it be possible to redirect to a specific page, or show a message saying 'please verify your email before continuing', if your app needed email verification?

To answer it simply – no, it's not a main mechanism and I think the name might be unfortunate. Your right, it's just an example implementation that covers very specific use case. By the time `isTokenValid` is called, the token  and signature is already validated, so the token `is` in fact valid. Better name would be `isUserAuthorized`, but I think I'll remove this method in future versions altogether, as it creates more confusion than it is useful.

 For now, if you'd like to redirect user to "Verify email before continuing" page you can do it in `handleValidToken` and just set  `isTokenValid` to `() => true`. In `v0.7` you'd be able to remove it altogether (I promise)
 
 
> 3.) Presumably I don't actually need to check for if(tenant.id), since authentication should already have been handled by the middleware here?

Yes, if you made sure that `/profile` route is only viewed by authenticated users, as in this example:

```typescript
    handleInvalidToken: async () => {
        // Avoid redirect loop
        if (request.nextUrl.pathname === "/login") {
          return NextResponse.next();
        }
  
        // Redirect to /login?redirect=/prev-path when request is unauthenticated
        const url = request.nextUrl.clone();
        url.pathname = "/login";
        url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
        return NextResponse.redirect(url);
    },
```

This will make sure that if `/profile` is rendered, `getTokens` or `getTokensFromObject` would return an actual tenant.

Despite that fact, interface of `getTokens` returns `null` in some cases. For example, if it was called on a page that wasn't handled correctly by the middleware, or in authentication page (usually by a mistake). So a good TypeScript developer practice want's us to handle both cases. You should have at least some logic (like "Something went wrong" message) when tenant is `null` in `/profile`.

By the way, remember to correctly set and test `matcher` in `middleware.ts` to make sure it's being called for your route:

```typescript
// middleware.ts
export const config = {
  matcher: ["/", "/((?!_next/static|favicon.ico|logo.svg).*)"], // handle all paths other than /_next/static, /favicon.ico or /logo.svg
};
```

> When initially logging in and visiting this page, the businesses are successfully retrieved. When saving a change, or refreshing the page, it would appear that firestore doesn't "remember" its authentication and throws the error Uncaught FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options). which I know to be the error indicating that login information was lost.

You are using Firestore web client to fetch data on the client side. `next-firebase-auth-edge` library is dedicated for backend authorization – to put it simply, it allows you to render user-dedicated content on server side. Once user is logged in, `/api/login` is called (and the secure cookies are set), `next-firebase-auth-edge` does not work with `firebase` client libraries.

You seem to be fetching user-dedicated content on the web client. Although it's not considered a bad practice (if you're using firebase access rules correctly), it's generally more safe to serve it through some closed environment like a server or lamda, edge-function.

What I would do in this case is to setup `/api/users/[userId]/businesses` api route that uses `getTokensFromObject` (like in [this example](https://github.com/awinogrodzki/next-firebase-auth-edge#api-routes-or-getserversideprops)), and then uses `firebase-admin` library to fetch data from the database and return them as .json. A quick example would be:

```typescript
// pages/api/users/[userId]/businesses.ts

import admin from 'firebase-admin';
import { getTokensFromObject } from "next-firebase-auth-edge/lib/next/tokens";

const initializeApp = ({ projectId, clientEmail, privateKey }: FirebaseOptions) => {
  return admin.initializeApp({
    credential: admin.credential.cert({
      projectId,
      clientEmail,
      privateKey,
    }),
  });
};

export const getFirebaseAdminApp = (options: FirebaseOptions) => {
  if (admin.apps.length > 0) {
    return admin.apps[0] as admin.app.App;
  }

  // admin.firestore.setLogFunction(console.log);

  return initializeApp(options);
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  const { userId } = req.query
  
  const db = getFirestore(getFirebaseAdminApp(YOUR_OPTIONS));
  const tokens = await getTokensFromObject(context.req.cookies, {
    apiKey: "firebase-api-key",
    cookieName: "AuthToken",
    cookieSignatureKeys: ["secret1", "secret2"],
    serviceAccount: {
      projectId: "firebase-project-id",
      privateKey: "firebase service account private key",
      clientEmail: "firebase service account client email",
    },
  });
  
  if (!tokens) {
    return res.status(403).send();
  }
  
  const snapshot = await db.collection('businesses').where('user_id', '==', tokens.decodedToken.uid).get();
  const businesses = [];
  
  for (const doc of snapshot.docs) {
     businesses.push(doc.data());
  }
  
  res.status(200).json({ businesses });
}
```

Then on the client side you just call GET `/api/users/[userId]/businesses` with given user ID and `Authorization: Bearer [idToken]`. `idToken` get be either the one passed from the server using `getTokens`  or the one from firebase authentication web client retrieved by `getIdTokenResult()`

Please note that the last example was not tested – I popped it out of my head on the run, so it might have some bugs in it, but it should be accurate enough :-)

Cheers 🎉

**Comment by awinogrodzki** [comment]
By the way, using it through `/api/users/[userId]/businesses` would enable you to load data in server component and render the list on server side, which would greatly improve user experience :-)

**Comment by clarencefoy** [comment]
Good morning! I can't believe what a thorough explanation you have provided and so quickly. 
I appreciate this very, very much. Let me try this out and I'll edit this comment with results.

**Comment by awinogrodzki** [comment]
Hey @clarencefoy!

You figured it out perfectly. 

1. You're right, there's no need to pass firebase options down to initializeApp, it can read from config directly. I copy-pasted code from my mono-repo implementation where I actually needed to pass those options

2.  NextApiResponse<Data> was also a copy paste, good you have updated it. :-) 
3.  You can use const { userId } = req.query as `uid`, but it's worth to check if given user matches user in token as a security measure and return 403 error otherwise

> I do wonder whether there is a Typescript-conformant way to insert something different here, like an error string.
What I do is standardised way for errors. Whenever error happens on API site, I return `ApiError` structure as json:

```typescript
export interface ApiError {
  type: string;
  detail: string;
  status: number;
  title: string;
}
```

You could update response to `NextApiResponse<Business[] | ApiError>` and then:

```typescript
if (!tokens) {
  return res.status(403).json({
    type: 'FORBIDDEN',
    detail: 'No credentials found in request cookies',
    status: 403,
    title: 'Forbidden'
  });
}
```

> I am casting doc.data() to my type of Business.
It's okay to cast in TypeScript if you have certainty the data will match the interface. It's good practice to add additional validation though – I use `joi` library ([link](https://github.com/hapijs/joi)) to validate inputs. 

> Feels a bit 'wrong' to just set setBusinesses(await response.json()); and also having to convert to json again,

Actually, it's exactly how this communication should go. Backend gets data from db, serializes it to JSON string, sends it to client, client receives the response and converts it back to JSON object. It's exactly what firebase client library does under the hood as well :-)

Another thing I did not cover is error handling. When you do:

```typescript
        const response = await fetch(`/api/users/${tenant.id}/businesses`);
        setBusinesses(await response.json());
        setBusinessesLoading(false);
```

Assuming you are returning `ApiError` in case of 403, you'd have to handle it like so:

```typescript
```

**Comment by clarencefoy** [comment]
Amazing, thank you for your help. The tips on error handling are particularly useful, as I want to implement this properly from the get-go.

I have one more question and then I'll get out of your hair:

I'm trying to exclude "/" from the automatic redirect to login. 

Now, I have disabled anonymous login, meaning "/" appears unauthenticated until a user clicks 'login'. (so the homepage will list businesses in the DB without authentication, as I'm making a public business directory)

I can see where the check against authentication initiates the redirects to login, but I can't see how to exclude a route from these checks. Do you have any pointers?

What adds a complication is the fact that `/` will be both an authenticated and unauthenticated page. If that's too difficult to achieve, I suppose I could split them into `/home` `/home_logged_in` or something like that.

Thank you for all your help, I'll leave you be after this one!

**Comment by clarencefoy** [comment]
I am closing this issue, as I don't want you to have to stare at this open issue for ages, when it's been resolved, really.

I wanted to add some information for anyone else searching this, about API routes in NextJS 12 vs 13.

The example app uses `/pages/api` for API routes, whereas in NextJS 13, these have been replaced by [route handlers](https://nextjs.org/docs/app/building-your-application/routing/router-handlers) and there's a fair few gotchas trying to migrate to this new way of doing things:

First, route handlers now go into /app/api and at the root of each folder (which turns into a route automatically), a route.ts file is defined, like so:

![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/77112468/c04665fb-6729-4d1a-8873-44fe7b0da576)

Dynamic parts of the route are still in brackets.

Within each route.ts file, you define GET, POST, PATCH...etc. all the standard methods seem to be supported. So a GET `/homepage_data` works, so long as there's a GET function within route.ts within the `homepage_data` folder.

I'll go through the next gotchas using the `get_businesses` function, as it's a bit more involved:

I initially ignored that the NextJS examples only use a `(req: Request)`, and no response in the function definition. That turns out to be a big deal, as params won't show up if there's a req and res field. What do I mean by that? Let's look at how the example app defines a function:

```export async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Business[]>
) {}
```

This now becomes:

```export async function GET(
  req: NextApiRequest,
  {
    params,
  }: {
    params: { email: string };
  }
) {}
```

As you can see, there's now only a request, followed by the params, which equal the dynamic parts of the route (the folders in brackets, like `[email]`).

The next gotcha was how to make the `getTokensFromObject` function work again. This expects a type `Partial<{[x: string]: string; }>`, telling me it's an object with string keys and string values. I think...my Typescript ignorance is showing.

Anyway, there's a convenience function within NextJS 13 api route handlers, called cookies, so we do: `import { cookies } from "next/headers";`

I hand that to a function which compiles the cookies into a cookie object and hands that into `getTokensFromObject`, like so:
```
  const tokens = await getTokensFromObject(returnCookieObject(cookies()), {
    ...tokenConfig,
  });
```

`returnCookieObject` is:

```
import { ReadonlyRequestCookies } from "next/dist/server/web/spec-extension/adapters/request-cookies";
export const returnCookieObject = (cookieStore: ReadonlyRequestCookies) => {
  let cookieObject: Partial<{
    [x: string]: string;
  }> = {};
  for (let cookie of cookieStore.getAll()) {
    cookieObject[cookie.name] = cookie.value;
  }

  return cookieObject;
};
```

This gets us authed calls again!

Now we just need to deal with the missing response, by creating a new response object as needed, so in case of an error:

```
  if (!tokens) {
    new Response('forbidden', {
      status: 403,
      headers: {},
    });
  }
```

or in case of success:

```
  return new Response(JSON.stringify(myData), {
    status: 200,
    headers: {},
  });
```

And that's it, welcome to NextJS 13 :)

Oh and don't forget to look at the error handling tips by @awinogrodzki above, which are most useful.
