### ISSUE TITLE
middleware not adding user token to cookies. " node_modules\next-firebase-auth-edge\lib\auth\jwt\utils.js (49:18) @ replace"

### ISSUE THREAD

**Issue by SethY8s** [awinogrodzki/next-firebase-auth-edge#59]
I have been following along with the static site example to implement Next and our firebase app. At first, I thought everything was going smoothly since I was getting my cookies updated when I logged in. It took me a while to figure this out, but my cookies were never changing. After some digging I found out that it was just creating an anonymous user each time I tried to sign in and the tokens in the cookies were staying the same. I was getting this small error on my server the entire time, but I never thought much of it. After working on this for a while not, I now belive this error is causing the middleware to not work as intended. 

To test if the middleware was actually working. I actually commented out all the anonymous login parts of the provider and middleware so a token would only be stored in the cookies if it was an actual user. After doing these changes, I was getting a 500 error on the /login API. If anyone has information about the small error message, I would really appreciate it since I am on a time crunch to get this finished. Down below is the full error and my middleware file(it is pretty much straight out of the static examples). I also added the client provider since that also was responsible for the anonymous token generation.

FULL ERROR:

```shell
- error node_modules\next-firebase-auth-edge\lib\auth\jwt\utils.js (49:18) @ replace
- error Cannot read properties of undefined (reading 'replace')
``` 

I  looked in the node modules and I do see they replace is used several times in that /auth/jwt/utils.js file. I have tried reinstalling it and my node modules several times and that has not resolved the issue.

My middleware.ts

```typescript
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import {
	authentication,
	refreshAuthCookies,
} from "next-firebase-auth-edge/lib/next/middleware";
import { getFirebaseAuth } from "next-firebase-auth-edge/lib/auth";
import { authConfig } from "./config/server-config";

function redirectToLogin(request: NextRequest) {
	if (request.nextUrl.pathname === "/login") {
		return NextResponse.next();
	}

	const url = request.nextUrl.clone();
	url.pathname = "/login";
	// url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
	url.search = `${url.search}`;

	// return NextResponse.redirect(url);
}

const { setCustomUserClaims, getUser } = getFirebaseAuth(
	authConfig.serviceAccount,
	authConfig.apiKey
);

export async function middleware(request: NextRequest) {
	return authentication(request, {
		loginPath: "/api/login",
		logoutPath: "/api/logout",
		...authConfig,
		handleValidToken: async ({ token, decodedToken }) => {
			if (request.nextUrl.pathname === "/api/custom-claims") {
				await setCustomUserClaims(decodedToken.uid, {
					someClaims: ["someValue"],
				});

				const user = await getUser(decodedToken.uid);
				const response = new NextResponse(
					JSON.stringify(user.customClaims),
					{
						status: 200,
						headers: { "content-type": "application/json" },
					}
				);

				await refreshAuthCookies(token, response, authConfig);
				return response;
			}

			return NextResponse.next();
		},
		handleInvalidToken: async () => {
			return redirectToLogin(request);
		},
		handleError: async (error) => {
			console.error("Unhandled authentication error", { error });
			return redirectToLogin(request);
		},
	});
}

export const config = {
	matcher: ["/", "/((?!_next/static|favicon.ico|logo.svg).*)"],
};

``` 

My auth provider:

```typescript
export const AuthProvider: React.FC<AuthProviderProps> = ({
	defaultTenant,
	children,
}) => {
	const { getFirebaseAuth } = useFirebaseAuth(clientConfig);
	const firstLoadRef = useRef(true);
	const [tenant, setTenant] = useState(defaultTenant);

	const handleIdTokenChanged = async (firebaseUser: FirebaseUser | null) => {
		if (firebaseUser && tenant && firebaseUser.uid === tenant.id) {
			firstLoadRef.current = false;
			return;
		}

		const auth = await getFirebaseAuth();

		// if (!firebaseUser && firstLoadRef.current) {
		// 	const { signInAnonymously } = await import("firebase/auth");
		// 	firstLoadRef.current = false;
		// 	const credential = await signInAnonymously(auth);
		// 	await fetch("/api/login", {
		// 		method: "GET",
		// 		headers: {
		// 			Authorization: `Bearer ${
		// 				(
		// 					await credential.user.getIdTokenResult()
		// 				).token
		// 			}`,
		// 		},
		// 	});
		// 	return;
		// }

		if (!firebaseUser) {
			firstLoadRef.current = false;
			startTransition(() => {
				setTenant(null);
			});
			return;
		}

		firstLoadRef.current = false;
		const tokenResult = await firebaseUser.getIdTokenResult();
		startTransition(() => {
			setTenant(mapFirebaseResponseToTenant(tokenResult, firebaseUser));
		});
	};

	const registerChangeListener = async () => {
		const auth = await getFirebaseAuth();
		const { onIdTokenChanged } = await import("firebase/auth");
		return onIdTokenChanged(auth, handleIdTokenChanged);
	};

	useEffect(() => {
		const unsubscribePromise = registerChangeListener();

		return () => {
			unsubscribePromise.then((unsubscribe) => unsubscribe());
		};
	}, []);

	return (
		<AuthContext.Provider
			value={{
				tenant,
			}}
		>
			{children}
		</AuthContext.Provider>
	);
};
``` 

Thank you in advance and if you need more information feel free to ask.

**Comment by awinogrodzki** [comment]
Hey @SethY8s,

It looks like your passing `undefined` as one of the `authConfig` options. Could you ensure you have `.env` file in the root of your project with all the variables? 

I would start by logging out `authConfig` to console and see if all of the following options are present:

```
  firebaseApiKey: process.env.FIREBASE_API_KEY!,
  serviceAccount: {
    projectId: process.env.FIREBASE_PROJECT_ID!,
    clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
    privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY!.replace(/\\n/g, "\n"),
  },
```

**Comment by SethY8s** [comment]
@awinogrodzki Thank you! I found out my private key needed quotations for whatever reason. After that, it ran smoothly!

**Comment by masads** [comment]
I still having issue.I tired @SethY8s solution but didn't worked.

export const serverConfig = {
    firebaseApiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
    serviceAccount: {
        projectId: process.env.FIREBASE_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY!.replace(/\\n/g, "\n"),
    },
};

export async function middleware(request: NextRequest) {
    console.log(serverConfig)
    return authentication(request, {
        loginPath: "/login",
        logoutPath: "/",
        apiKey: serverConfig.firebaseApiKey,
        cookieName: "AuthToken",
        cookieSignatureKeys: ["secret1", "secret2"],
        cookieSerializeOptions: {
            path: "/",
            httpOnly: true,
            secure: false, // Set this to true on HTTPS environments
            sameSite: "strict" as const,
            maxAge: 30 * 60 * 60 * 24 * 1000, // 30 days
        },
        serviceAccount: serverConfig.serviceAccount,
        checkRevoked: false,
        handleValidToken: async ({ token, decodedToken }) => {
            console.log("Successfully authenticated", { token, decodedToken });
            return NextResponse.next();
        },
        handleInvalidToken: async () => {
            // Avoid redirect loop
            if (request.nextUrl.pathname === "/login") {
                return NextResponse.next();
            }

            // Redirect to /login?redirect=/prev-path when request is unauthenticated
            const url = request.nextUrl.clone();
            url.pathname = "/login";
            url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
            return NextResponse.redirect(url);
        },
        handleError: async (error) => {
            console.error("Unhandled authentication error", { error });
            // Avoid redirect loop
            if (request.nextUrl.pathname === "/login") {
                return NextResponse.next();
            }

            // Redirect to /login?redirect=/prev-path on unhandled authentication error
            const url = request.nextUrl.clone();
            url.pathname = "/login";
            url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
            return NextResponse.redirect(url);
        },
    });
}


> @awinogrodzki Thank you! I found out my private key needed quotations for whatever reason. After that, it ran smoothly. Thank you for the great library!

**Comment by masads** [comment]
I follow the [next13-typescript-static-pages](https://github.com/awinogrodzki/next-firebase-auth-edge/tree/main/examples/next13-typescript-static-pages) example but I'm getting error:
```
- error node_modules\next-firebase-auth-edge\lib\auth\jwt\utils.js (49:18) @ replace
- error Cannot read properties of undefined (reading 'replace')
```
I also try @SethY8s Solution but it didn't worked

here's my code:
`export async function middleware(request: NextRequest) {
    console.log(serverConfig)
    return authentication(request, {
        loginPath: "/login",
        logoutPath: "/",
        apiKey: serverConfig.firebaseApiKey,
        cookieName: "AuthToken",
        cookieSignatureKeys: ["secret1", "secret2"],
        cookieSerializeOptions: {
            path: "/",
            httpOnly: true,
            secure: false, // Set this to true on HTTPS environments
            sameSite: "strict" as const,
            maxAge: 30 * 60 * 60 * 24 * 1000, // 30 days
        },
        serviceAccount: serverConfig.serviceAccount,
        checkRevoked: false,
        handleValidToken: async ({ token, decodedToken }) => {
            console.log("Successfully authenticated", { token, decodedToken });
            return NextResponse.next();
        },
        handleInvalidToken: async () => {
            // Avoid redirect loop
            if (request.nextUrl.pathname === "/login" || request.nextUrl.pathname === "/signup") {
                return NextResponse.next();
            }

            // Redirect to /login?redirect=/prev-path when request is unauthenticated
            const url = request.nextUrl.clone();
            url.pathname = "/login";
            url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
            return NextResponse.redirect(url);
        },
        handleError: async (error) => {
            console.error("Unhandled authentication error", { error });
            // Avoid redirect loop
            if (request.nextUrl.pathname === "/login") {
                return NextResponse.next();
            }

            // Redirect to /login?redirect=/prev-path on unhandled authentication error
            const url = request.nextUrl.clone();
            url.pathname = "/login";
            url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
            return NextResponse.redirect(url);
        },
    });
}

export const config = {
    matcher: ['/app', '/welcome', '/login', '/signup']
}`

**Comment by masads** [comment]
> I follow the [next13-typescript-static-pages](https://github.com/awinogrodzki/next-firebase-auth-edge/tree/main/examples/next13-typescript-static-pages) example but I'm getting error:
> 
> ```
> - error node_modules\next-firebase-auth-edge\lib\auth\jwt\utils.js (49:18) @ replace
> - error Cannot read properties of undefined (reading 'replace')
> null
> ```
> 
> I also try @SethY8s Solution but it didn't worked
> 
> here's my code:
> 
> ```
> import { NextRequest, NextResponse } from "next/server";
> import { serverConfig } from "./config/server-config";
> import { authentication } from "next-firebase-auth-edge/lib/next/middleware";
> 
> export async function middleware(request: NextRequest) {
>     console.log(serverConfig)
>     return authentication(request, {
>         loginPath: "/login",
>         logoutPath: "/",
>         apiKey: serverConfig.firebaseApiKey,
>         cookieName: "AuthToken",
>         cookieSignatureKeys: ["secret1", "secret2"],
>         cookieSerializeOptions: {
>             path: "/",
>             httpOnly: true,
>             secure: false, // Set this to true on HTTPS environments
>             sameSite: "strict" as const,
>             maxAge: 30 * 60 * 60 * 24 * 1000, // 30 days
>         },
>         serviceAccount: serverConfig.serviceAccount,
>         checkRevoked: false,
>         handleValidToken: async ({ token, decodedToken }) => {
>             console.log("Successfully authenticated", { token, decodedToken });
>             return NextResponse.next();
>         },
>         handleInvalidToken: async () => {
>             // Avoid redirect loop
>             if (request.nextUrl.pathname === "/login" || request.nextUrl.pathname === "/signup") {
>                 return NextResponse.next();
>             }
> 
>             // Redirect to /login?redirect=/prev-path when request is unauthenticated
>             const url = request.nextUrl.clone();
>             url.pathname = "/login";
>             url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
>             return NextResponse.redirect(url);
>         },
>         handleError: async (error) => {
>             console.error("Unhandled authentication error", { error });
>             // Avoid redirect loop
>             if (request.nextUrl.pathname === "/login") {
>                 return NextResponse.next();
>             }
> 
>             // Redirect to /login?redirect=/prev-path on unhandled authentication error
>             const url = request.nextUrl.clone();
>             url.pathname = "/login";
>             url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
>             return NextResponse.redirect(url);
>         },
>     });
> }
> 
> export const config = {
>     matcher: ['/app', '/welcome', '/login', '/signup']
> }
> ```
> 
> ```
> export const serverConfig = {
>     firebaseApiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
>     serviceAccount: {
>         projectId: process.env.FIREBASE_PROJECT_ID!,
>         clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
>         privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY!.replace(/\\n/g, "\n"),
>     },
> };
> ```

@awinogrodzki Can you please help?
