### ISSUE TITLE
Images are no longer loading after I added next-firebase-auth-edge

### ISSUE THREAD

**Issue by rgbskills** [awinogrodzki/next-firebase-auth-edge#65]
After I added and implemented next-firebase-auth-edge none of the images are loading, I believe that the middleware matcher is at fault but I don't know for sure, did anyone had issues like this? 

NOTES
After I log in images start to work again.
If I add the image in the "PUBLIC_PATHS" list it also works
`const PUBLIC_PATHS = ["/", "/logo.svg" ,"/register", "/login", "/reset-password"];`

Here is a screenshot of my folder structure:
<img width="382" alt="images_issue" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/5773622/82a23f21-c8c5-452c-abc6-1886a0d4ccf2">

my images are in the root of the public folder

**Comment by awinogrodzki** [comment]
Hey @rgbskills,

Does your `middleware.ts` export `config` object similar to the one below?

```typescript
export const config = {
  matcher: ["/", "/((?!_next|favicon.ico|api).*)", "/api/login", "/api/logout"],
};
```

`"/((?!_next|favicon.ico|api).*)",` entry is the one you need. It will omit middleware processing entirely for files in `public` dir.

**Comment by rgbskills** [comment]
hey @awinogrodzki 

here is my middleware export config:

```export const config = {
  matcher: ["/", "/((?!_next|favicon.ico|api).*)", "/api/login", "/api/logout"],
};```

Also here is the codebase, env's will be rotated, and the project will be open sourced once I get all the features implemented.
https://github.com/rgbskills/undercover

**Comment by awinogrodzki** [comment]
@rgbskills

You are right. I have tested your project and `"/((?!_next|favicon.ico|api).*)"` matcher is not working as I expected. It still does allow files to be intercepted by a middleware causing the redirect. I have fixed it by this:

```typescript
export const config = {
  matcher: ["/", "/((?!_next|favicon.ico|api|.*\\.).*)", "/api/login", "/api/logout"],
};
```

Let me know how it works for you :-)

**Comment by rgbskills** [comment]
Thank you so much 👍

**Comment by rgbskills** [comment]
Solved
