### ISSUE TITLE
Implement fix from https://github.com/vercel/next.js/issues/45981

### ISSUE THREAD

**Issue by mxswat** [awinogrodzki/next-firebase-auth-edge#70]
Hi, great work on the project, and I'm enjoying the new examples you made.

I would like to mention to you a minor issue that happened during development: https://github.com/vercel/next.js/issues/45981

It's a fairly easy fix, and I wonder if you are interested in implementing it.

Let me know if you have any alternative solution in mind.

**Comment by mxswat** [comment]
Amazing! Thank you!

**Comment by awinogrodzki** [comment]
Resolved in `next-firebase-auth-edge@0.8.0`
