### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by dukeofsoftware** [awinogrodzki/next-firebase-auth-edge#84]
Hi! I can't access login or register page because of too many redirects. I copied everything from example

```tsx
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { authentication } from "next-firebase-auth-edge/lib/next/middleware";
import { authConfig } from "./config/server-config";

const PUBLIC_PATHS = ["/register", "/login", "/reset-password","/"];

function redirectToHome(request: NextRequest) {
  const url = request.nextUrl.clone();
  url.pathname = "/";
  url.search = "";
  return NextResponse.redirect(url);
}

function redirectToLogin(request: NextRequest) {
  if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
    return NextResponse.next();
  }

  const url = request.nextUrl.clone();
  url.pathname = "/login";
  url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
  return NextResponse.redirect(url);
}

export async function middleware(request: NextRequest) {
  return authentication(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: authConfig.apiKey,
    cookieName: authConfig.cookieName,
    cookieSerializeOptions: authConfig.cookieSerializeOptions,
    cookieSignatureKeys: authConfig.cookieSignatureKeys,
    serviceAccount: authConfig.serviceAccount,
    handleValidToken: async ({ token, decodedToken }) => {
      // Authenticated user should not be able to access /login, /register and /reset-password routes
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }

      return NextResponse.next();
    },
    handleInvalidToken: async () => {
      return redirectToLogin(request);
    },
    handleError: async (error) => {
      console.error("Unhandled authentication error", { error });
      return redirectToLogin(request);
    },
  });
}

export const config = {
  matcher: ["/", "/((?!_next|favicon.ico|api|.*\\.).*)", "/api/login", "/api/logout"],
};
```

**Comment by awinogrodzki** [comment]
Hey @dukeofsoftware!

Thanks for reporting. Could you upload your network activity when running app locally? You can do so, by navigating to `Network` tab in `Chrome Dev Tools`:

<img width="792" alt="Screenshot 2023-08-11 at 13 44 18" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/12574743/730298c1-4cdf-4487-8d1c-ecb8da1fdb12">

It should produce `.har` file. You can send it via e-mail to: amadeusz.winogrodzki@gmail.com

It will help me to figure out the cause of redirects

**Comment by dukeofsoftware** [comment]
![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/89215036/f1f8b7ce-051d-41e4-8092-7806cbe35fb4)

I sent .har file via email

**Comment by dukeofsoftware** [comment]
https://github.com/dukeofsoftware/series-tracker-v2
github repository

**Comment by awinogrodzki** [comment]
@dukeofsoftware thanks for the repo. I was able to reproduce the issue.

The issue is caused by `trailingSlash: true` in `next.config.js`. https://github.com/dukeofsoftware/series-tracker-v2/blob/main/next.config.js#L12
 It basically forces slash at the end of each page path, which causes the following check to fail, causing redirect loop:
 ```tsx
  if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
    return NextResponse.next();
  }
 ```
 
 If you wish to continue using `trailingSlash: true` option, you should update your `PUBLIC_PATHS` to look as follows:
 ```tsx
 const PUBLIC_PATHS = ["/register/", "/login/", "/reset-password/","/"];
 ```

Let me know if that helps!

**Comment by dukeofsoftware** [comment]
It worked. Thank you so much

**Comment by Artemdanilov5** [comment]
Hi @awinogrodzki 
I have updated it `const PUBLIC_PATHS = ["/register/", "/login/", "/reset-password/","/"];`
but it's not working correct. 
If I am not authorized - I'm not getting redirect from homepage and always see "You are logged in Go to profile page"
If I'm trying to authorize - I'm getting 307 error(permanary redirect)
Can you test it again please?

**Comment by awinogrodzki** [comment]
Hey @Artemdanilov5,

Could you share the contents of your `next.config.js` and `middleware.ts` files?

Also, please share the output of `npx next info` command run inside your project's root folder

**Comment by Artemdanilov5** [comment]
@awinogrodzki I just clone all your code and have in `next.config.js`

```
module.exports = {
  trailingSlash: true,
}
```
I have only updated this line in `middleware.ts` : `PUBLIC_PATHS = ["/register/", "/login/", "/reset-password/","/"];`
as you recommended above

**Comment by awinogrodzki** [comment]
@Artemdanilov5,

It seems that Next.js now also forces trailing slash in API Routes. 

You would have to update `loginPath` and `logoutPath`, as well as `matcher` config in `middleware.ts`:

```tsx
authMiddleware(request, {
    loginPath: '/api/login/',
    logoutPath: '/api/logout/',
    ...otherOptions
});
```

```tsx
export const config = {
  matcher: [
    '/',
    '/((?!_next|favicon.ico|api|.*\\.).*)',
    '/api/login/', // Needs trailing slash
    '/api/logout/' // Needs trailing slash
  ]
};

```
