### ISSUE TITLE
No API login path

### ISSUE THREAD

**Issue by Vicidevs** [awinogrodzki/next-firebase-auth-edge#85]
In your login example use used this code

```
const idTokenResult = await credential.user.getIdTokenResult();
      await fetch("/api/login", {
        method: "GET",
        headers: {
          Authorization: `Bearer ${idTokenResult.token}`,
        },
      });
```

But practically, you didn't create the /api/login route. Though it works fine in development mode but in production it is giving me error. Or should I create the api/login route instead of the api/custom-claim? But I like your library. Thanks

**Comment by awinogrodzki** [comment]
Hey @Vicidevs!

`/api/login` and `/api/logout` routes are handled inside `middleware.ts`. You don't need to define those routes yourself.

What error are you having?

**Comment by awinogrodzki** [comment]
Closing the issue as resolved. Feel free to comment if you have any other questions 🍻

**Comment by Alick1997** [comment]
Was this resolved? I am running into a similar issue where no /api/login path exists, even though I defined the middleware as showed in the docs.

**Comment by Alick1997** [comment]
> Was this resolved? I am running into a similar issue where no /api/login path exists, even though I defined the middleware as showed in the docs.

Issue stemmed from defining middleware.ts file inside app directory. Should be defined in src.
