### ISSUE TITLE
token not deleted after logout

### ISSUE THREAD

**Issue by dukeofsoftware** [awinogrodzki/next-firebase-auth-edge#86]
Hi! I want to delete the token after logout. 
![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/89215036/3e226c60-c69f-4d06-b322-7a435b3cc9d7)
![image](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/89215036/463071e6-6e4d-4639-91df-49f06dac355a)

**Comment by abel-vs** [comment]
same here, any suggestions?

**Comment by awinogrodzki** [comment]
Hey @dukeofsoftware!

What do you mean by "token not deleted"? Does the browser still sends authentication cookies after calling `/api/logout`?

**Comment by dukeofsoftware** [comment]
Hi! Thanks for your helps. I solved it.
