### ISSUE TITLE
Use with Firebase Cloud Functions

### ISSUE THREAD

**Issue by fetimo** [awinogrodzki/next-firebase-auth-edge#87]
Hey Amadeusz, thanks for the great, well-written library. 

This might be too implementation-specific but I am trying to use this library in conjunction with `firebase/functions` in a similar way to the example connecting to Firestore in the examples folder.  

It works fine for unauthenticated calls but if the cloud function itself checks if the call was authenticated, it is undefined. `firebase/functions` [calls an internal context to get auth data](https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/service.ts#L284) and passes that to the request.  

I can think of a couple of workarounds: 1) rely on the browser to call the cloud function; 2) write a proxy API route hosted with Node.js to make the call. Ideally, I want to keep the call server-side and the proxy solution negates all the benefits that hosting at the edge gives us.

I suspect the answer is 'no' but are you aware of any way to make this library and authenticated Firebase Cloud Functions compatible?

**Comment by awinogrodzki** [comment]
Hey @fetimo!

I am not that familiar with `firebase/functions`. I've looked into docs and the code, but I have some questions that hopefully you can answer:

1. Could you describe your use-case? I assume you are calling `firebase/functions` from `middleware.ts`. Could you provide some example code of this usage?
2. I see that `firebase/functions` is compatible with Node.js environment, but `firebase-js-sdk` holds mainly client side libraries. Do you know any official example on how to authenticate `firebase/functions` on Node.js side? 
3. "write a proxy API route hosted with Node.js to make the call.". Could you provide some simple example of such API route? 

If `firebase/functions` is able to authenticate in Node.js environments and works inside Edge environment, it should be possible to integrate `next-firebase-auth-edge` with `firebase/functions`. 

If I can find out how the internal auth context is setup, I could replicate that for `firebase/functions`.

There is still possibility that official code required to setup such context may not be compatible with Edge runtimes. In such case, proxy API route seems like a best approach.

**Comment by fetimo** [comment]
1. Sure! It's very similar to your example where it fetches data (the counter) from the database, the only difference is that instead of calling the database our data is fetched via a cloud function to reduce rewriting code for different clients. So in the /profile/UserProfile/page.tsx file it calls the cloud function to get various bits of user data.
2. You're spot on, it is more geared to browser environments. I couldn't find any official examples of doing it so I've probably made an assumption that that's supported.
3.  I slept on it and figured the most straightforward way to do this is to bypass the `firebase/functions` library altogether and just write a simple fetch like so (NB. needs error handling to be added):
```
const callCloudFunction = async (name: string, data: unknown) => {
  try {
    const tokens = await getTokens(cookies(), authConfig);

    const req = await fetch(
      `https://us-central1-${clientConfig.projectId}.cloudfunctions.net/${name}`,
      {
        method: 'POST',
        body: JSON.stringify({ data: data }),
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${tokens?.token}`
        }
      }
    );

    const res = await req.json();
    return res.result;
  } catch (error) {
    console.log('callCloudFunction error', error);
  }
};
```
This, I believe, solves my issue and although it requires a bit of boilerplate it's essentially what the `firebase/functions` library boils down to.
