### ISSUE TITLE
no-kid-in-header-error - regression from 0.7.6 to 0.8.0

### ISSUE THREAD

**Issue by anmilleriii** [awinogrodzki/next-firebase-auth-edge#89]
Hello, I believe there is a regression in token decoding from 0.7.6 --> 0.8.0, perhaps related to the switch to `jose`?. 

**Environment**

- Nx monorepo
- Next 13.4.8
- next-firebase-auth-edge 0.8.0
- Firebase 10.1.0

**Error**

```
- error ../node_modules/.pnpm/next-firebase-auth-edge@0.8.0_next@13.4.8/node_modules/next-firebase-auth-edge/lib/auth/token-verifier.js (72:15) @ FirebaseTokenVerifier.mapJoseErrorToAuthError
- error Internal error: no-kid-in-header-error
```

Just providing a quick report I can provide a reproduction if required, thanks.

**Solution**

Pinning to 0.7.6 works.

**Comment by awinogrodzki** [comment]
Hey @anmilleriii!

Thanks for reporting. This issue has been already solved in https://github.com/awinogrodzki/next-firebase-auth-edge/issues/82

You need to update `next-firebase-auth-edge` to `0.8.3` :-)

Let me know if that works!
