### ISSUE TITLE
getTokensFromObject returns empty on  versions >0.7.6

### ISSUE THREAD

**Issue by nelsonweze** [awinogrodzki/next-firebase-auth-edge#94]
I just upgraded to `0.8.6` and I noticed  `getTokensFromObject` wasn't returning the tokens. Had to downgrade back to `0.7.6`.
Tried on different next versions including `13.4.19` and issue persists.

**Comment by awinogrodzki** [comment]
Hey @nelsonweze. Thanks for reporting.

I created pages api route that's using `getTokensFromObject` from `0.8.6` and wasn't able to reproduce the issue.

You can test it here: https://next-firebase-auth-edge-starter.vercel.app/api/tokens
Here's the code that's calling `getTokensFromObject`: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/pages/api/tokens.ts

Are you calling `getTokensFromObject` from API route or getServerSideProps?

**Comment by nelsonweze** [comment]
Hi @awinogrodzki I am calling it inside API route.  Strangely `getTokens` works fine in Server Components

**Comment by heavyengineer** [comment]
hey, i had the same problem a few weeks back, but didn't know if it was me or the code as i was fiddling with a whole heap of stuff. I've copied notes from our trello below. I think it comes down to when revalidate path is called in the app directory (perhaps only in the api context) then the cookies get nuked. Because of other stuff i ended up cutting my losses and instead of using the cookie verification throughout the app, i'm doing the cookie stuff in middleware (which works fine) then i'm going to set up a new jwt to talk to the other services. (for now i'm just setting clear text  headers(we're not live yet))
----------
Next headers cookies has is not defined after the set cookies in app router
https://github.com/vercel/next.js/issues/52437
https://github.com/vercel/next.js/issues/53322

and has some significant issues in other areas:
Next caches `POST` , `PUT` and `DELETE` requests  if the request returns a `200 OK` status code even with `Authorization` header present
https://github.com/vercel/next.js/issues/52405

**Comment by awinogrodzki** [comment]
@heavyengineer thanks for adding some context on this one!

@nelsonweze, let's try to do some experiments for me to better understand the issue. 

Could you update to `next-firebase-auth-edge@0.8.6`, and check if the authentication cookies are present before calling `getTokensFromObject`? 

Just log out the parameter you are passing to `getTokensFromObject`. 

I want to understand if the issue is connected with invalid cookies or empty cookies

**Comment by nelsonweze** [comment]
@awinogrodzki I tried that earlier and the cookies object wasn't empty. Did that again and here's the output.
HoWever, the output of `getTokensFromObject` still remains null.

`{
  'session.sig': 'VnlO_aEy7bpnDa1AZXpBnMZLYgoCMimeF9nKVbop2fA',
  session: 'eyJpZFRva2VuIjoiZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltRmtOV00xWlRsbU5UZGpPV0kyTkRZell6ZzFPRFExWVRBNE9UbGhPV1EwTVRJNU1tTTRZek1pTENKMGVYQWlPaUpLVjFRaWZRLmV5SnVZVzFsSWpvaVRtVnNjMjl1SUVWNlpTSXNJblI1Y0dVaU9pSm9iM04wSWl3aWFYTnpJam9pYUhSMGNITTZMeTl6WldOMWNtVjBiMnRsYmk1bmIyOW5iR1V1WTI5dEwyNWxjM1IxWjJVdFpHVjJNU0lzSW1GMVpDSTZJbTVsYzNSMVoyVXRaR1YyTVNJc0ltRjFkR2hmZEdsdFpTSTZNVFk1TlRNNE5UWTVNeXdpZFhObGNsOXBaQ0k2SW14VlpYZEdhMjFDT0dSUWFHbEtWVkJzVUdsUllsVnVXVTA0U1RNaUxDSnpkV0lpT2lKc1ZXVjNSbXR0UWpoa1VHaHBTbFZRYkZCcFVXSlZibGxOT0Vreklpd2lhV0YwSWpveE5qazFNemcxTmprekxDSmxlSEFpT2pFMk9UVXpPRGt5T1RNc0ltVnRZV2xzSWpvaWJtVnNjMjl1UUc1bGMzUjFaMlV1WTI5dElpd2laVzFoYVd4ZmRtVnlhV1pwWldRaU9uUnlkV1VzSW1acGNtVmlZWE5sSWpwN0ltbGtaVzUwYVhScFpYTWlPbnNpWjI5dloyeGxMbU52YlNJNld5SXhNVEV4TURjMU16WTBNVEV5TmpFMk1ESTBNakFpWFN3aVpXMWhhV3dpT2xzaWJtVnNjMjl1UUc1bGMzUjFaMlV1WTI5dElsMTlMQ0p6YVdkdVgybHVYM0J5YjNacFpHVnlJam9pWTNWemRHOXRJbjE5LkxRbnEzQzZkbHl0OW5HQjJmVUFyTWtJZ1AxWGgtaVlmZmJkY1ZONlZySUdOY0dENGIyU1ZLWVlHcUJ4bUI3Mk1rZXBaQzNKbldzN1NiYU1FbE9nZG9uWTdtUmplM09NUlNmd2x5T1d5N2VOMS1GNVhCUWZ2U0ZJTW1ySGZPaHlteGMyVWUzREdkWmlvUXpRR0djRWlBaUxTcG54VFZ4Vlp1OFhudTdibzRIVVZINmYzYkkwUE9tR2I5clZPd1VBR2p3TlJfNjVIeTB0eFFlYkVOQ1VCUllQTG80Tk5tY3pSR01XRXNiOTRCemJ0TmRVQ3h0NGJQUmUzZVhfMWxONVdtV3dUWUF0QnBoWUZ0WTJQSGNmd1RFQ2JZRVlXOFRuVjNoUXVaOW9XNGZ6S1JTMUw5M3dpUkVnazZwRXdlZ2FoZ3BLUUJwYkY3Q3EyY3hfbkxRTVd5USIsInJlZnJlc2hUb2tlbiI6IkFNZi12Qnh2cDhmWGxmVHVPNVFqdDFvREhoZllMc0c5NEswXzhudEpzbHJjY1BkLWl2V05udXA5czNJRE5nTjdsbFFucVJRNzlSb3dFZTdjZlRRa0N1ZjhkMVplMzNCb29Kc1NvbVlMTjg2Z28tM0I2SXVaVGlyNkFkWlNLVnhLS2xMdlE3WkZLMkNTLTF4blRtVmFyUE5ScmIwY0VMYnpKYW81MVhYRC05cFhOTGdYTkM5NS1CYyJ9'
}
`

**Comment by awinogrodzki** [comment]
@nelsonweze could you install `next-firebase-auth-edge@0.8.7-1` and test if that solved the issue?

If not, could you change `cookieSignatureKeys` to `['secret1', 'secret2']` and check if it works?

It seems that cookies are present, and token is valid, but signature is not verified correctly

**Comment by nelsonweze** [comment]
@awinogrodzki  I tried the steps and I am still getting same result.

**Comment by awinogrodzki** [comment]
@nelsonweze, could you copy-paste your API route code, where you've been using `getTokensFromObject`? Is it under `pages` or `app` folder? 

Would it be possible to show here the contents of your `middleware.ts` file? It would help me to reproduce the issue on my side.

Last question, just to be clear, the issue happens in local or production environment, or both?

**Comment by awinogrodzki** [comment]
You can also run `npx next info` in project directory, so I can get glimpse at what Node.js and React versions you're using

**Comment by nelsonweze** [comment]
@awinogrodzki  I am using in pages and it happens on both local and staging, didn't try on prod.
```js
export const decodeToken = async (
  cookies: Record<string, any>
): Promise<DecodedIdToken | undefined> => {
  let decoded: DecodedIdToken | undefined;
  try {
    const tokens = await getTokensFromObject(cookies, fbAuthEdgeOptions());
    decoded = tokens?.decodedToken;
    console.log(decoded);
  } catch (err) {
    console.log(err);
  }
  return decoded;
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  await initFirebase();
  const token = await decodeToken(req.cookies);
  if (!token) {
    handleUnAuthorized(res);
    return;
  }

 ...
```

middleware.ts

```js
export async function middleware(req: NextRequest) {
  const headers = new Headers(req.headers);

  headers.set('X-XSS-Protection', '1; mode=block');
  headers.set('X-Frame-Options', 'SAMEORIGIN');
  headers.set('Content-Security-Policy', "frame-ancestors 'self';");

  const privateKey = process.env.FIREBASE_PRIVATE_KEY!.replace(/\\n/gm, '\n');

  return authentication(req, {
    loginPath: '/api/login',
    logoutPath: '/api/logout',
    apiKey: process.env.FIREBASE_API_KEY!,
    cookieName: 'session',
    cookieSignatureKeys: ['secret1', 'secret2'],
    cookieSerializeOptions: {
      path: '/',
      httpOnly: true,
      secure: isProd,
      sameSite: 'lax' as const,
      maxAge: 12 * 60 * 60 * 24 * 1000, // twelve days
    },
    serviceAccount: {
      projectId,
      privateKey,
      clientEmail,
    },
    checkRevoked: true,
    handleValidToken: async ({ token, decodedToken }) =>
      redirectToPage(headers, req, decodedToken, token),
    handleInvalidToken: async () => redirectToLogin(req, headers),
  });
}

export const config = {
  matcher: ['/', '/((?!_next/static|favicon.ico|logo.svg|api/v1).*)'],
};
```

npx next info 
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.27.1
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

**Comment by awinogrodzki** [comment]
@nelsonweze, could you show contents of `fbAuthEdgeOptions()` ? Are those options the same as ones you pass to the middleware?

**Comment by nelsonweze** [comment]
Yes, it is

**Comment by awinogrodzki** [comment]
Hello @nelsonweze! Any updates on the issue? Were you able to test it with `0.8.8-1`?

**Comment by nelsonweze** [comment]
@awinogrodzki  Apologies, I missed your earlier message.

I tested with the version and token is still null. 

```javascript
[DEBUG][#94] RotatingCredential match key {
  signedKey: 'Wz2kHlSNW8x9fpYw72Ne2_S6ekaw0M30SNdA_HOCluM',
  digest: 'Wz2kHlSNW8x9fpYw72Ne2_S6ekaw0M30SNdA_HOCluM'
}
[DEBUG][#94] RotatingCredential verify {
  data: 'eyJpZFRva2VuIjoiZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqbGhOVEU1TURjME5tVTVNMkpoWlRJME9XSXlZV0UzWXpKaFlUUmxNekEyTTJVek5ERmxZemNpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnVZVzFsSWpvaVRtVnNjMjl1SUVWNlpTSXNJblI1Y0dVaU9pSm9iM04wSWl3aWFYTnpJam9pYUhSMGNITTZMeTl6WldOMWNtVjBiMnRsYmk1bmIyOW5iR1V1WTI5dEwyNWxjM1IxWjJVdFpHVjJNU0lzSW1GMVpDSTZJbTVsYzNSMVoyVXRaR1YyTVNJc0ltRjFkR2hmZEdsdFpTSTZNVFk1TmpVeE1qYzJOeXdpZFhObGNsOXBaQ0k2SW14VlpYZEdhMjFDT0dSUWFHbEtWVkJzVUdsUllsVnVXVTA0U1RNaUxDSnpkV0lpT2lKc1ZXVjNSbXR0UWpoa1VHaHBTbFZRYkZCcFVXSlZibGxOT0Vreklpd2lhV0YwSWpveE5qazJOVEV5TnpZM0xDSmxlSEFpT2pFMk9UWTFNVFl6Tmpjc0ltVnRZV2xzSWpvaWJtVnNjMjl1UUc1bGMzUjFaMlV1WTI5dElpd2laVzFoYVd4ZmRtVnlhV1pwWldRaU9uUnlkV1VzSW1acGNtVmlZWE5sSWpwN0ltbGtaVzUwYVhScFpYTWlPbnNpWjI5dloyeGxMbU52YlNJNld5SXhNVEV4TURjMU16WTBNVEV5TmpFMk1ESTBNakFpWFN3aVpXMWhhV3dpT2xzaWJtVnNjMjl1UUc1bGMzUjFaMlV1WTI5dElsMTlMQ0p6YVdkdVgybHVYM0J5YjNacFpHVnlJam9pWTNWemRHOXRJbjE5LmF3ZXYwVGNfREd4YlRDa1pmY1NibHU1b0RpcFczYXZoY2lFSlBWNjhqWHB1N2t0eF9ZaVpHQUZOV3QyNm9ubGZiRS1hT2xKbmVNcl9oc0hFTmdLcUtLcnh5d0ZZU21qSFZaQjFocEI0UW5IWURPTTB5cWhPV0tpSk5za0Q4Qy1wVXFZWm1SQ1Z2X05hWU1VajFvUjhNSFdJb2FZYlREVDZyR0xTeGNXSmhxYm5ERTAtSU9QUVlrTUxUMkZ2aHdyMHRWSkptRU1zTE9hcklCUlNsb0pzdTY4UjlnTUV0RXQ1ZlFPQXJielFvT0RXb1hwdHdwRW9ycElqYXplMlpJYzUwN19LczREU0RFZnpJM2FIemZGejN1cVc3WURkek5IZXdqUzUyM2lHVTd5UzNCSUtuY3RCRWNzcDdDbU1CTWljX0Q3cDZHZF9GZjV1S3Y1MV90a19QQSIsInJlZnJlc2hUb2tlbiI6IkFNZi12Qnd0N1V2NXJNVVpDRzZLd1JvSmNQSUNpS3BOZWVQQWhvTExUTHF0VG02cExCOHpXRzRWT3JqOXhvR2g3ZDNHSzByQkphZ1o5ZU54c2g3RFFNQWswdFBXNS1CbV9ucVl5elNhcUpkQnM0ZjQydm5lMExVS3drOGpacjFmOVo1Nl9qbXI5cHdZalZsa25PUkZmZjE1QWhVWEJKZTFBYWdhNlJuQVJlTmgyelh5RlgwOEJ5MCJ9',
  digest: 'Wz2kHlSNW8x9fpYw72Ne2_S6ekaw0M30SNdA_HOCluM',
  matchingKeyIndex: 0
}
[DEBUG][#94] RotatingCredential match key {
  signedKey: 'Wz2kHlSNW8x9fpYw72Ne2_S6ekaw0M30SNdA_HOCluM',
  digest: 'Wz2kHlSNW8x9fpYw72Ne2_S6ekaw0M30SNdA_HOCluM'
}
tokens null
tokens null
```

**Comment by awinogrodzki** [comment]
@nelsonweze, what about logs between `[DEBUG][#94] getTokensFromObject start` and `[DEBUG][#94] getTokensFromObject result`?   We are particularly interested in `getCookiesTokens` and `RotatingCredential` logs that happen between `getTokensFromObject start` and `getTokensFromObject result`.

**Comment by awinogrodzki** [comment]
You should see those logs when calling `getTokensFromObject`

**Comment by nelsonweze** [comment]
So sorry man for the waste of time.  I use mono repo for my project and I just realized I was using two different versions of this package in the project. Updated both of them to this and it works. 
Thank you so much! You've been so helpful. Apologies again

**Comment by awinogrodzki** [comment]
@nelsonweze no worries. Glad we have sorted this out! Cheers :-)
