### ISSUE TITLE
Actually no issue

### ISSUE THREAD

**Issue by rossanodr** [awinogrodzki/next-firebase-auth-edge#98]
I just want to say that this repository is amazing.
amazing work you did here
congrats

**Comment by suntudo** [comment]
Absolutely -- this is a great project and @awinogrodzki is one of the most helpful and responsive maintainers I've seen. Have you considered adding a Buy me a Coffee link?

**Comment by awinogrodzki** [comment]
Thank you @rossanodr @suntudo, you're too kind!  :-)

This library wouldn't be as it is without lots of feedback and testing from other developers. Kudos to all contributors and users as well!

> Have you considered adding a Buy me a Coffee link?

To be honest, I wasn't expecting such positive feedback. I guess it would not hurt to get an extra cup of coffee :D I will definitely consider it. Thank you!
